### ISSUE TITLE
Add another variable that allows to toggle session.cookie_secure

### ISSUE THREAD

**Issue by zigazajc007** [serversideup/docker-php#105]
### Affected Docker Images

All of them

### Current Behavior

session.cookie_secure = 1 is currently hard-codded and can't be changed with variables.

### Expected Behavior

Another variable that can change session.cookie_secure

### Steps To Reproduce

Every cookie will include secure tag, so cookies won't work on insecure / http websites.

### Host Operating System

Fedora 37

### Docker Version

```markdown
Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        baeda1f
 Built:             Tue Oct 25 18:02:36 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true
```

**Comment by jaydrogers** [comment]
This is resolved in the v3 of the Docker images (coming soon).

It was resolved in this commit: https://github.com/serversideup/docker-php/commit/c8d848a72d007f86168360d322f2822f98669869

Status of the v3 is located here: https://github.com/serversideup/docker-php/pull/207
