### ISSUE TITLE
Add overview and repo to each docker image on DockerHub

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#11]
# Background
* I need to figure out how to fill in the data
* Adding this information will add more legitimacy and clarity to the images on DockerHub
<img width="1277" alt="Screen Shot 2021-03-10 at 9 02 07 AM" src="https://user-images.githubusercontent.com/3174134/110649665-6b8a7d80-817f-11eb-99d4-8c83cecade8b.png">

# Expected Results
* PHPDocker.io has a great example

<img width="1278" alt="Screen Shot 2021-03-10 at 9 01 10 AM" src="https://user-images.githubusercontent.com/3174134/110649742-80ffa780-817f-11eb-9d38-e23f195b75c0.png">

# Where I left off
* I did some quick searching how to find this, but immediate results were unsuccessful. Will try this again later

**Comment by jaydrogers** [comment]
Update: I found it under the "Builds" tab at the top, but I was hoping to automate the linking.

Might have to manage everything manually (including the overview).

**Comment by szepeviktor** [comment]
Here you go: https://github.com/christian-korneck/docker-pushrm/blob/master/README-containers.md
