### ISSUE TITLE
Design a landing page website

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#111]
### 🎨 Figma Design File
https://www.figma.com/file/WuVX7tgB46clFe3mXmNWcV/PHP-Docker-Website?node-id=0%3A1&t=lb7EZWjiitOeOFYq-1

<a href="https://www.figma.com/file/WuVX7tgB46clFe3mXmNWcV/PHP-Docker-Website?node-id=2%3A3&t=lb7EZWjiitOeOFYq-1">![Image](https://user-images.githubusercontent.com/3174134/214933369-fac570ba-f988-4240-a1e8-e88a98b2ae94.png)</a>

## Server Side Up Project Selector
![Image](https://user-images.githubusercontent.com/3174134/214934154-91d47d3b-9b10-424c-a5a8-5dc1f6c15c07.png)

**Demo:** https://www.figma.com/proto/Ii5v10tUCe7sZf0EKOwM02/Server-Side-Up---Logo-%26-Brand?page-id=901%3A315&node-id=915%3A605&viewport=1447%2C278%2C0.84&scaling=min-zoom&starting-point-node-id=915%3A605&show-proto-sidebar=1

**Navigation**
- [x] Link SSU logo to homepage
- [x] On hover, animate the lighter color for the hover state
- [x] Link the social icons with a hover state as well

**Search**
- [x] Trigger the Algolia built-in search
<img width="557" alt="image" src="https://user-images.githubusercontent.com/3174134/215155619-14ff17ad-d7d0-4bda-b3ae-ace00ba98fbf.png">

**Browse Products**
![Image](https://user-images.githubusercontent.com/3174134/214934883-78338f18-0f7c-41cb-afce-eb3cbbad1fb6.png)
- [x] Show all of our products
- [x] Underline the text on hover
- [x] Clicking off the menu should close the menu
- [x] Ensure the shadow is there on the white box

## Header
![image](https://user-images.githubusercontent.com/3174134/214965355-80916c6b-3e07-4d19-b0c4-c5c79afe7558.png)
- [x] Link the logo to the homepage of the project
- [x] Apply hover states to all buttons

## Hero section
![Image](https://user-images.githubusercontent.com/3174134/214936002-e47eeb70-ef38-4568-baed-d2d9a257f356.png)

- [x] Loop video
- [x] Ensure it scales well for mobile

**Search**
- [x] Clicking search should trigger the full screen Algolia view
<img width="447" alt="image" src="https://user-images.githubusercontent.com/3174134/215156153-419ddc15-f0f1-42a1-9f8f-6a4a944f2dcf.png">

## Optimized for Laravel
![Image](https://user-images.githubusercontent.com/3174134/214936052-d4178245-c2a2-47d4-b89a-405e6c3ac5a3.png)

- [x] Loop video
- [x] Ensure it scales well for mobile

## Testimonials

![Image](https://user-images.githubusercontent.com/3174134/214936203-21021927-fb28-4932-8a34-c1f0861f18aa.png)

**Tweets to embed**
- [ ] https://twitter.com/fideloper/status/1556730170966511617
- [ ] https://twitter.com/jaydrogers/status/1587838520735027207

**Display**
- [ ] Can we force the dark mode tweet? (if not, I can design a custom testimony box)

## Get started
![image](https://user-images.githubusercontent.com/3174134/214937166-3b1b8c95-491a-4914-83b9-c3ebe127b508.png)
- [x] The link to this is TBD at the moment because we need the documentation built first

## Community
![image](https://user-images.githubusercontent.com/3174134/214937335-c4030e90-c19d-44fb-b273-96abad3651a6.png)

- [x] Link our social profiles
- [x] Apply an animated text color on hover
- [x] Link the icons to the profiles as well (no color change for the icons though)

# 📲 Mobile specific
Mobile specific designs can be found here: https://www.figma.com/file/WuVX7tgB46clFe3mXmNWcV/PHP-Docker-Website?node-id=55%3A372&t=zuqSzV0PdloZSRFb-11

- [x] Most fonts decrease in size
- [x] Scale videos to fit, and ensure they autoplay & loop

### Mobile menu
Deigns: https://www.figma.com/file/WuVX7tgB46clFe3mXmNWcV/PHP-Docker-Website?node-id=64%3A296&t=zuqSzV0PdloZSRFb-11

<img width="615" alt="image" src="https://user-images.githubusercontent.com/3174134/215170363-10b82ef4-ec73-43ec-8545-295aee4e709c.png">

- [x] If the `X` could animate in (like 521dimensions.com), that would be awesome!

<img width="524" alt="image" src="https://user-images.githubusercontent.com/3174134/215170918-16e2d5e8-6887-4f9d-a894-83764f592a96.png">

- [x] Include the docs on the mobile menu and show the active page

### Search
<img width="369" alt="image" src="https://user-images.githubusercontent.com/3174134/215171151-6017102d-ae73-459c-a896-6b6ac9b250cb.png">

- [x] Use the full screen algolia search

**Comment by danpastori** [comment]
@jaydrogers Could you link to the Figma component for the Server Side Up menu? I need to grab the menu styles for shadow and links.

**Comment by jaydrogers** [comment]
For sure. I’m on my mobile, but I’ll call you to explain where it’s at.
