### ISSUE TITLE
Create user documentation

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#112]
# Blocked By
https://github.com/serversideup/docker-php/issues/115

# Outline of Docs

### Getting Started
- [x] Introduction
- [x] These images vs. others
   - More performant than the official images (show tweet)
   - Make use the Ondrej repos
   - Based on Ubuntu 22.04
   - Easily extensible with S6 Overlay (easy to add other services if needed)
   - Images are optimized for Laravel & WordPress
- [x] Installation
- [x] Upgrade guide
   - Latest vs tagged versions
   - Explain upgrade cycles
   - Ensure you are using CI & automated tests
   - Tagged versions must have their own updates (`apt update && apt upgrade`)
   - Subscribe to our repo for latest releases
- [x] Choosing a host
- [x] Changelog
- [x] About the project
- [x] Contributing

### Guide
- [x] Choosing the right image
    - CLI vs FPM vs Apache vs NGINX
    - Explain upgrade cycles
    - Link to upgrade guide
- [x] Customizing the image
    - The `webuser` is a standard user that you can change the UID
    - Link to environment variables
    - Adding custom PHP configurations
    - Adding a custom NGINX config
    - Adding custom Apache Config
    - Adding services via S6 Overlay
- [ ] Troubleshooting
    - DEBUG_MODE
- [x] Building your own application images
    
### Laravel
- [x] Automations script
- [x] Task Scheduler
- [x] Laravel Queue
- [x] Horizon + Redis Queue

### WordPress
- [x] Deployment example
- [x] WordPress optimizations

### Reference
- [x] Environment Variable Specifications

**Comment by danpastori** [comment]
@jaydrogers I pushed a preview of the docs and the functionality should be ready for you to start experimenting with. In the push, I included a little structure to get started. Let me know if you have questions.
