### ISSUE TITLE
Automatically deploy website changes on release

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#114]
# Problem
* We need the Docker PHP repository to be the single source of truth for the website, but also exist on serverisdeup.net

# Proposed solution
- [x] Automate GitHub pages deployments (from `main`)
- [ ] Create a proxy from serversideup.net to route serversideup.net/open-source/php-docker-images to the GitHub Pages

**Comment by jaydrogers** [comment]
@danpastori and I met today, the Apache proxy for WordPress was too much of a hassle. We will trigger the Proxy via CloudFlare.

**Comment by zigazajc007** [comment]
Then you can also use Cloudflare Pages to deploy static websites like docs for free and benefit from low latency from everywhere on the world and be protected from DDOS attacks (The power of CDN and static websites). So you can completely replace Github Pages.

**Comment by jaydrogers** [comment]
Good point!

Looking into GitHub Pages more, it seems like its great that it's baked into GitHub, but there are a lot of random issues that people have.

I might look into doing CloudFlare Pages for the whole thing.

**Comment by zigazajc007** [comment]
Cloudflare Pages can connect to your github repository and every time you will push new code to the main branch Cloudflare Page will auto update the website.

**Comment by jaydrogers** [comment]
I have the previews working here: https://github.com/serversideup/docker-php/pull/120

Thanks @zigazajc007!
