### ISSUE TITLE
Ensure dynamic sitemaps are being built and submitted to Google

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#117]
# Problem
- Google doesn't know what pages to index

# Proposed solution
- [x] Use a Nuxt library to dynamically generate sitemaps
- [ ] Extend the serversideup.net sitemap to include this project's sitemap for indexing

**Comment by danpastori** [comment]
@jaydrogers What will the "root" domain of these images be from SSU? Will it be `https://serversideup.net/open-source/docker-php`

**Comment by jaydrogers** [comment]
@danpastori: Yup!

**Comment by danpastori** [comment]
Perfect. On launch we will have to update the serversideup.net site map, but this should be ready.
