### ISSUE TITLE
Design and implement open graph social images

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#118]
## Problem
- When someone shares a page on a social media site, there isn't a social image to make the link more engaging

## Solution
- [x] Design an open graph image to be published on a social share
- [x] Implement the open graph image into Nuxt Content

## More details
<img src="https://user-images.githubusercontent.com/3174134/218802942-e8d1b344-302c-4cc5-8d6b-1620f1af2d0f.png" >

**Figma board: https://www.figma.com/file/WuVX7tgB46clFe3mXmNWcV/PHP-Docker-Website?node-id=141%3A470&t=eqvQ5a32jO8alTxW-11**

**Comment by danpastori** [comment]
@jaydrogers Could you resize that image for the following dimensions:

FB: 1200x630 (https://blog.hootsuite.com/social-media-image-sizes-guide/#Facebook_image_sizes)
Twitter: 2:1 Aspect ratio so like 1200x600 (https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/summary-card-with-large-image) I don't really know about Twitter, I've seen multiple references.
