### ISSUE TITLE
Determine which PHP packages are absolutely needed

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#12]
# Background
* We need to determine which packages are **absolutely** needed

# What we have now
Here are the packages that we are currently using:
```
php7.4-cli
php7.4-common
php7.4-curl
php7.4-fpm
php7.4-gd
php7.4-json
php7.4-mbstring
php7.4-mysql
php7.4-soap
php7.4-sqlite3
php7.4-xml
php7.4-zip
```

These are very different from what PHPDocker.io are using:
```
php7.4-apcu
php7.4-apcu-bc
php7.4-cli
php7.4-curl
php7.4-json
php7.4-mbstring
php7.4-opcache
php7.4-readline
php7.4-xml
php7.4-zip
```

Here's a diff (ours left, theirs right)
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/3174134/110651957-878f1e80-8181-11eb-95fb-fa448dc81be9.png">

# Next Steps
* @danpastori do you have any thoughts on what is needed?

### Goal
I would like to make these images as small as possible.

**Comment by szepeviktor** [comment]
Why don't you replicate Debian's way of distributing PHP extensions?

```
$ apt-cache depends php7.4-fpm | grep php
php7.4-fpm
  Depends: php7.4-cli
  Depends: php7.4-common
  Depends: php7.4-json
  Depends: php7.4-opcache
  Suggests: php-pear
```

Then install **all** other packages from the PPA.

Then disable them.

All scripted! :)

This way it will fit every use-case.

**Comment by jaydrogers** [comment]
Thanks for pointing that out! I will follow those basics, but likely pull them all from [Ondrej's PHP](https://launchpad.net/~ondrej/+archive/ubuntu/php) (since its a widely accepted in the PHP community).

I have had issues in the past where Ubtuntu's repos took a while to process the update.

I will be starting off with Ubuntu images (since that's what we're comfortable with now) but will be making the transition to Debian/Alpine sometime in the future.

**Comment by jaydrogers** [comment]
Thanks! I might keep things simple for now and loop back for more flexibility later. Worst case scenario, people can build their own image on top of mine if they need custom packages.

**Comment by szepeviktor** [comment]
> people can build their own image

That will result in a near-zero user base 😿

**Comment by jaydrogers** [comment]
I understand, its a complex story...

### Goal
* We want people to be able to work with us on other PHP projects
* We want anyone in the world to have the closest replication of our production images as possible

![DockerImageDependency](https://user-images.githubusercontent.com/3174134/110656563-ac859080-8185-11eb-9f50-6a18e18a488f.png)


### What this project is not
* I don't expect people to flood to this project on day one. It's mainly to make it easier for others to work with us on some other open source PHP projects

### First problem to solve
* Get an open image out to people so we can replicate environments

### Future problem to solve
* Make it really flexible for people to customize

I definitely **do not** disagree with what you are proposing. I just want to get some sort of PHP out there (strictly for testing) and I can come back to cleaning it up later.

**Comment by jaydrogers** [comment]
It seems like all of the packages we have have been working well for what we need 👍
