### ISSUE TITLE
dpkg: error processing package php8.1-fpm

### ISSUE THREAD

**Issue by dragonfire1119** [serversideup/docker-php#127]
### Affected Docker Images

serversideup/php:8.1-fpm

### Current Behavior

```
ARG PHP_VERSION=8.1

RUN apt-get update && apt-get install -y --no-install-recommends \
    php${PHP_VERSION}-bcmath
```

My CI keeps erroring out with: `dpkg: error processing package php8.1-fpm`.

I have not changed the Dockerfile so I'm guessing it's something that changed recently.

### Expected Behavior

My CI to build successfully with PHP Extensions able to be installed.

### Steps To Reproduce

Add a `php8.1-bcmath` extension to a Dockerfile and it should error out. 
I've taken everything out and narrowed it down to PHP extensions. 

### Host Operating System

Linux

### Docker Version

```markdown
Client:
 Cloud integration: v1.0.29
 Version:           20.10.22
 API version:       1.41
 Go version:        go1.18.9
 Git commit:        3a2c30b
 Built:             Thu Dec 15 22:28:41 2022
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Desktop 4.16.2 (95914)
 Engine:
  Version:          20.10.22
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.9
  Git commit:       42c8b31
  Built:            Thu Dec 15 22:25:43 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.14
  GitCommit:        9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by dragonfire1119** [comment]
> Thanks for the detailed bug report!
> 
> I have a feeling this is running into an error because of the modifications to `www.conf`. Instead of modifying that file, I am going to append to it.
> 
> ### Workaround
> * Use `--option=Dpkg::Options::="--force-confdef"` to set the default to use the existing version of `www.conf`
> 
> ### Your example with a fix
> ```dockerfile
> ARG PHP_VERSION=8.1
> 
> RUN apt-get update && apt-get install -y --no-install-recommends --option=Dpkg::Options::="--force-confdef" \
>     php${PHP_VERSION}-bcmath
> ```
> 
> Let me know if that works!

Thanks for the prompt response! This seems to have resolved the issue. Just to be sure, I'm rerunning the CI. In any case, thorough bug reports save time! Thank you for your time on this.

**Comment by jaydrogers** [comment]
I am closing this issue because it is no longer relevant to the v3 structure.

We made major changes, so be sure to read this: https://release-v3-0.docker-php.pages.dev/docs/guide/migrating-from-v2-to-v3

How to install an extension is located here: https://release-v3-0.docker-php.pages.dev/docs/guide/installing-additional-php-extensions
