### ISSUE TITLE
We need HTML page titles

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#130]
![Screenshot](https://public-assets.bugflow.io/projects/5/bugs/361/1676386532-screenshot.png)

🌎 URL
-----

https://feature-v2-2-0-documentation.docker-php.pages.dev/

⚡️ Reported By
--------------

Jay Rogers

🔎 More details
--------------

**Resolution:** 2560x1440

**Viewport Dimensions:** 1280x1330

📎 Attachments
-------------

**Comment by danpastori** [comment]
I have this working for the home page. By default, the page title is the first H1 on the page for docs. There's an open discussion here: https://github.com/nuxt/content/issues/1896 about not being able to adjust.

The other option is to force each h1 to be an h2 and manually set the title.

**Comment by jaydrogers** [comment]
Are there any workarounds to adjust that title?

Look at this example where it just says `Introduction`, which is weird.

![Image](https://user-images.githubusercontent.com/3174134/220430992-79f7d694-81a3-49b6-8301-e5f0007b3bd0.png)

**Comment by danpastori** [comment]
@jaydrogers Check out `/docs/content/docs/1.index.md`. You have to set the `head.title` in the front matter.
