### ISSUE TITLE
Algolia search needs to be connected

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#131]
# TODO
- [ ] Connect on Desktop
- [ ] Connect for mobile

![Screenshot](https://public-assets.bugflow.io/projects/5/bugs/362/1676386922-screenshot.png)

🌎 URL
-----

https://feature-v2-2-0-documentation.docker-php.pages.dev/

⚡️ Reported By
--------------

Jay Rogers

🔎 More details
--------------

**Resolution:** 2560x1440

**Viewport Dimensions:** 1280x1330

📎 Attachments
-------------

**Comment by danpastori** [comment]
@jaydrogers So I found out this is what we need to apply for: https://docsearch.algolia.com/docs/who-can-apply

I have everything set up for Algolia, we just need to apply for this functionality. It's what all the other docs sites use.

**Comment by danpastori** [comment]
We also need to add the following to the Nuxt ENV:
```
ALGOLIA_API_KEY=XXX
ALGOILA_APPLICATION_ID=XXX
ALGOLIA_INDEX=docker_php_docs_dev
```

**Comment by jaydrogers** [comment]
Just adding a note, the crawler needs to be scoped to https://serversideup.net/open-source/docker-php/docs/

Waiting to hear back from support on this. @danpastori: Can you handle this?

**Comment by jaydrogers** [comment]
@danpastori: Just following up on this.

It seems Algolia is still not connected.

Should I flag this as "help wanted"?

**Comment by jaydrogers** [comment]
@danpastori: This error appeared in Spin's logs when running Nuxt content.

Not sure if this is related or leaves a clue:

```
[2:49:32 PM] [nuxt] [runtimeConfig] You are trying to access a public runtime config value (algolia) directly from the top level. This currently works (for backward compatibility with Nuxt 2) but this compatibility layer will be removed in v3.5. Instead, you can update config['algolia'] to config.public['algolia'].
```

**Comment by jaydrogers** [comment]
@danpastori: Algolia got back and here is what they had to say

![Screenshot 2023-09-11 at 18-05-24 Confused by account set up – Algolia](https://github.com/serversideup/docker-php/assets/3174134/1c4a992e-8b90-4cad-a94a-f301874bf754)
