### ISSUE TITLE
Configure a place to set link variables (default to #3B82F6)

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#139]
![Screenshot](https://public-assets.bugflow.io/projects/5/bugs/370/1676479945-screenshot.png)

🌎 URL
-----

http://localhost:3000/docs/getting-started/these-images-vs-others#why-do-we-need-multiple-processes

⚡️ Reported By
--------------

Jay Rogers

🔎 More details
--------------

**Resolution:** 2560x1440

**Viewport Dimensions:** 1280x804

📎 Attachments
-------------

**Comment by danpastori** [comment]
Added this color to the `tailwind.config.js` file. Easiest way to do the override.
