### ISSUE TITLE
When I go to a sub-page directly, I am getting a blank page (likely a 500 error)?

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#143]
![Screenshot](https://public-assets.bugflow.io/projects/5/bugs/374/1676487976-screenshot.png)

🌎 URL
-----

https://feature-v2-2-0-documentation.docker-php.pages.dev/docs/

⚡️ Reported By
--------------

Jay Rogers

🔎 More details
--------------

**Resolution:** 2560x1440

**Viewport Dimensions:** 1280x1302

📎 Attachments
-------------

**Comment by danpastori** [comment]
I believe this is resolved with a previous bug. Closing for now.

**Comment by jaydrogers** [comment]
This is not resolved. Moving back to development
