### ISSUE TITLE
For some reason, this is including headings from my "index" page

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#145]
![Screenshot](https://public-assets.bugflow.io/projects/5/bugs/376/1676497768-screenshot.png)

🌎 URL
-----

https://feature-v2-2-0-documentation.docker-php.pages.dev/docs/getting-started/these-images-vs-others

⚡️ Reported By
--------------

Jay Rogers

🔎 More details
--------------

**Resolution:** 2560x1440

**Viewport Dimensions:** 2560x1302

📎 Attachments
-------------

**Comment by danpastori** [comment]
I believe this issue is resolved in a previous bug as well.

**Comment by jaydrogers** [comment]
This was not resolved
