### ISSUE TITLE
Should we link back to the "index" page?

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#146]
## Problem
- I can visit the "index" by hitting "Docs" in the navigation
- Once I hit that navigation, I don't see it in the sidebar

![Screenshot](https://public-assets.bugflow.io/projects/5/bugs/377/1676497915-screenshot.png)

🌎 URL
-----

https://feature-v2-2-0-documentation.docker-php.pages.dev/docs/getting-started/these-images-vs-others

⚡️ Reported By
--------------

Jay Rogers

🔎 More details
--------------

**Resolution:** 2560x1440

**Viewport Dimensions:** 1280x1302

📎 Attachments
-------------

**Comment by danpastori** [comment]
I added the index page to the top of the navigation.
