### ISSUE TITLE
If I go to these links, I get a 500 error

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#149]
![Screenshot](https://public-assets.bugflow.io/projects/5/bugs/380/1676502261-screenshot.png)

🌎 URL
-----

http://localhost:3000/docs/getting-started/

⚡️ Reported By
--------------

Jay Rogers

🔎 More details
--------------

**Resolution:** 2560x1440

**Viewport Dimensions:** 1280x1302

📎 Attachments
-------------

**Comment by danpastori** [comment]
@jaydrogers Do you want a URL at the `/docs/getting-started` endpoint? If so, we need to add an `index.md`. Otherwise, I'll try to redirect somewhere else.

**Comment by jaydrogers** [comment]
Weird... I thought this was a valid link.

Nah, we will just close it.

/close
