### ISSUE TITLE
Add the grid from the homepage here

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#150]
![Screenshot](https://public-assets.bugflow.io/projects/5/bugs/381/1676502668-screenshot.png)

🌎 URL
-----

https://feature-v2-2-0-documentation.docker-php.pages.dev/docs

⚡️ Reported By
--------------

Jay Rogers

🔎 More details
--------------

**Resolution:** 2560x1440

**Viewport Dimensions:** 1280x1302

📎 Attachments
-------------

**Comment by danpastori** [comment]
This was referred to as the "guide". I added this to the home page (1.index.md). Swap out and remove what you don't want.
