### ISSUE TITLE
I added a new line here, but it displays on the same line with no space

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#156]
![Screenshot](https://public-assets.bugflow.io/projects/5/bugs/438/1677860865-screenshot.png)

🌎 URL
-----

http://localhost:3000/docs/getting-started/installation

⚡️ Reported By
--------------

Jay Rogers

🔎 More details
--------------

**Resolution:** 1728x1117

**Viewport Dimensions:** 1728x966

📎 Attachments
-------------

**Comment by danpastori** [comment]
Since it's a leading paragraph, it's intended to be 1 paragraph per component. This doesn't affect SEO or page structure, so I added another `::lead-p` below it.
