### ISSUE TITLE
Okay @szepeviktor, time to roast me!

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#16]
Hey @szepeviktor,

Thanks again for all of your help and feedback on these images. I really like learning from developers who are much smarter than me 🤓

**If you have the time or interest**, I would love to hear your feedback on what you think of these images.

### What I am looking for
* Are there any massive security issues? If so where?
* Anything that makes you cringe?
* How would you do things differently?
* What are the highest priorities that should be fixed first?

### Let us compensate you
If you have a PayPal (or whatever you use), we'd love to send a few bucks for your help. Just to be clear, it would probably be in the $50 to $100 USD ballpark, so don't spend hundreds of hours on this 😁

### Organizing things
If we can keep your feedback in this single thread, then I can create issues for each item you come up with.

Thoughts? 

If you're too busy... _no problem!_  We totally get it. You had a lot of great feedback earlier, so I wanted to just let you know that I am in a good spot to actually make changes now that things are working.

Hope you are doing well!

**Comment by szepeviktor** [comment]
Hello Jay!
This issue tells me _Please give me a Viktor in a container_.
Simply running a web application may result in horrible 👺 consequences. I cannot contribute to that. Sorry.

---

Caring about a web application - what I do - does not fit in a GitHub issue, it took 10 years from my life.
So it includes your mindset, analysis of service providers ... all the way up to paranoid monitoring.

- A container contains an almost complete (no kernel) [operating system](https://github.com/szepeviktor/debian-server-tools/blob/master/debian-setup/debian-setup.sh#L23-L40). Most people DO NOT care about it.
- Security is not another department in your company. Security consists of [baby steps](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/WordPress-security.md) throughout your development and operations.
- When configuring a web server software you may "just run it" or [prevent many incidents](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/apache-sites-available/Skeleton-site-ssl.conf).
- Running anything of the web means connecting to the open and wild Internet. There is no Internet Police, so it is up to you to defend against 50+% of Internet traffic (attacks).

So I have zero experience in the do-not-care way of running of a web application. It **will** have security issues. It will have non-zero general problems per day. I receive access and error log excerpts every morning. They contain no problems. When they do I act ASAP.

How could I help you??
