### ISSUE TITLE
Open Graph Images are not loading

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#161]
# Problem
- The open graph images are not loading for Twitter
- Facebook loads, but it shows an incorrect image

# Steps to replicate

### Twitter
Go to the Composer and paste in https://serversideup.net/open-source/docker-php/

<img width="634" alt="image" src="https://user-images.githubusercontent.com/3174134/223747457-93a43904-cf3f-466d-9676-689fded1a5e5.png">

### Facebook
Use the sharing tool debugger with the same URL (https://developers.facebook.com/tools/debug/)

![Screenshot 2023-03-08 at 08-50-27 Sharing Debugger - Meta for Developers](https://user-images.githubusercontent.com/3174134/223747654-43137a6e-3cb0-48d7-87f2-4ca8b2e20ce8.png)

**Comment by danpastori** [comment]
I think the image sizes need to be 1200x630 instead of 600. This is what the open graph tester shows which is right, just the images look scaled weird: https://www.opengraph.xyz/url/https%3A%2F%2Fserversideup.net%2Fopen-source%2Fdocker-php%2F

**Comment by jaydrogers** [comment]
I just updated the image, but it's still not appearing. Thoughts?

<img width="602" alt="image" src="https://user-images.githubusercontent.com/3174134/223765768-b04ca7ac-e66d-48ac-b542-0ad6236e3b43.png">

**Comment by jaydrogers** [comment]
This was fixed over screensharing 👍
