### ISSUE TITLE
APM agent php not starting

### ISSUE THREAD

**Issue by Lorrhanl** [serversideup/docker-php#164]
### Affected Docker Images

serversideup/php:8.1-fpm-nginx

### Current Behavior

I created a new docker image based on tag 8.1-fpm-nginx with elastic apm php installed. The apm doesn't work when start container, i receive this message:

PHP Warning:  Unknown: open_basedir restriction in effect. File(/opt/elastic/apm-agent-php/src/bootstrap_php_part.php) is not within the allowed path(s): (/var/www/html:/dev/stdout:/tmp) in Unknown on line 0
NOTICE: PHP message: PHP Warning:  Invalid callback \Elastic\Apm\Impl\AutoInstrument\PhpPartFacade::shutdown, class "\Elastic\Apm\Impl\AutoInstrument\PhpPartFacade" not found in Unknown on line 0.

The agent works fine on my other image php-fpm.

### Expected Behavior

elastic apm php working.

### Steps To Reproduce

1. Create a new image based serversideup/php:8.1-fpm-nginx
2. installing elastic apm agent
3. Run image created

### Host Operating System

Biglinux base manjaro

### Docker Version

```markdown
Client:
 Version:           23.0.1
 API version:       1.42
 Go version:        go1.20
 Git commit:        a5ee5b1dfc
 Built:             Sat Feb 11 13:58:04 2023
 OS/Arch:           linux/amd64
 Context:           default

Server:
 Engine:
  Version:          23.0.1
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.20
  Git commit:       bc3805a0a0
  Built:            Sat Feb 11 13:58:04 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.6.16
  GitCommit:        31aa4358a36870b21a992d3ad2bef29e1d693bec.m
 runc:
  Version:          1.1.4
  GitCommit:        
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Anything else?

Repository: https://github.com/elastic/apm-agent-php

Dockerfile:
FROM serversideup/php:8.1-fpm-nginx

ENV PHP_VERSION 8.1

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        php${PHP_VERSION}-dev \
        php${PHP_VERSION}-pgsql \
        php${PHP_VERSION}-mongodb \
        vim \
        && apt-get clean \
        && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

RUN curl -L -o /tmp/elastic.deb https://github.com/elastic/apm-agent-php/releases/download/v1.7.1/apm-agent-php_1.7.1_all.deb

RUN dpkg -i /tmp/elastic.deb

EXPOSE 80

**Comment by jaydrogers** [comment]
Thanks for your report!

I don't have any direct experience with running the Elastic APM agent, but I will attempt to take a look at this once I have some time free up (currently running a little behind schedule on some other things 😅)

I would be very grateful if others are able to chime in on this if they have experience! 🙌

**Comment by alexjustesen** [comment]
@Lorrhanl you'll want to tell PHP its ok to execute code in another directory. Got an example here where I need to be able to interact with a mounted `/config` dir.

https://github.com/alexjustesen/speedtest-tracker/blob/62bc2c3867f650ef29f030edc2f88262af949f16/Dockerfile#L3-L4

**Comment by Lorrhanl** [comment]
> /opt/elastic/apm-agent-php/src/

Tranks @alexjustesen, it's fixed my error. Really the problem was what you said.

**Comment by Lorrhanl** [comment]
> @Lorrhanl you'll want to tell PHP its ok to execute code in another directory. Got an example here where I need to be able to interact with a mounted `/config` dir.
> 
> https://github.com/alexjustesen/speedtest-tracker/blob/62bc2c3867f650ef29f030edc2f88262af949f16/Dockerfile#L3-L4

Thanks @alexjustesen, it's fixed my error. Really the problem was what you said.
