### ISSUE TITLE
Homepage broken: https://serversideup.net/open-source/docker-php/

### ISSUE THREAD

**Issue by divdax** [serversideup/docker-php#175]
### Affected Docker Images

-

### Current Behavior

-

### Expected Behavior

-

### Steps To Reproduce

-

### Host Operating System

-

### Docker Version

```markdown
-
```

**Comment by jaydrogers** [comment]
Thanks for letting me know!

Just adding for a future note in case this happens again. I think this had something to do with my GitHub Actions. On "PR Close", it triggered a preview build but somehow published that.

It never triggered my Deploy Static site.

![image](https://user-images.githubusercontent.com/3174134/232945089-473d7f48-bd9a-4b3a-a423-39beb90ec2c9.png)

### My fix
I applied this to see if this will improve the workflow. https://github.com/serversideup/docker-php/commit/3da700422d85ccdcd0dbf6a3e9583e856e9a9e6a
