### ISSUE TITLE
Suspicious images on Docker Hub

### ISSUE THREAD

**Issue by szepeviktor** [serversideup/docker-php#20]
https://hub.docker.com/r/serversideup/php 😲 

Please consider adding a readme and show how images are built from each other. Ubuntu > cli > fpm > fpm-*

**Comment by jaydrogers** [comment]
Great point!!! Thanks for pointing this out. Added to the next release.

**Comment by szepeviktor** [comment]
@jaydrogers Well done.

All that is left is that CLI is built on top of https://github.com/serversideup/docker-php/blob/main/php/7.4/cli/Dockerfile#L5

**Comment by jaydrogers** [comment]
Thanks for pointing this out!!

Just added it 😃
