### ISSUE TITLE
/composer/config.json is outside of php open_basedir settings

### ISSUE THREAD

**Issue by rsov** [serversideup/docker-php#221]
### Affected Docker Images

serversideup/php:8.2-fpm-nginx

### Current Behavior

[2023-11-24T04:18:12.261976+00:00] main.ERROR: Warning: is_file(): open_basedir restriction in effect. File(/composer/config.json) is not within the allowed path(s): (/var/www/html:/dev/stdout:/tmp) in /var/www/html/vendor/composer/composer/src/Composer/Json/JsonFile.php on line 85 [] []

### Expected Behavior

no crash plz

### Steps To Reproduce

try to run magento 2 in the image

### Host Operating System

WSL

### Docker Version

```markdown
Client: Docker Engine - Community
 Cloud integration: v1.0.35+desktop.5
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:32:16 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Desktop
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Anything else?

Solved by adding this to my dockerfile 

`ENV PHP_OPEN_BASEDIR="/var/www/html:/dev/stdout:/tmp:/composer"`

**Comment by jaydrogers** [comment]
Thanks for posting your solution!

### Solution from above
Configuring PHP_OPEN_BASEDIR fixes this error.
```
ENV PHP_OPEN_BASEDIR="/var/www/html:/dev/stdout:/tmp:/composer"
```
