### ISSUE TITLE
Expand Documentation

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#226]
### Discussed in https://github.com/serversideup/docker-php/discussions/167

<div type='discussions-op-text'>

<sup>Originally posted by **jaydrogers** March 22, 2023</sup>
# Problem
- The current documentation was a simple translation of what we currently had. There still seems to be a lot that should be explained to improve on-boarding

# Testing
Latest documentation can be viewed at: https://release-v3-0.docker-php.pages.dev/docs/

# Proposed Solution
Add documentation that covers the following topics:

### Getting started
- [x] **Default configurations**
  - Production-ready and optimized for Laravel & WordPress
  - Default installed PHP Modules
  - Link how to customize

### Guide
- [x] **Migrating from official PHP images**
   - Show an easy switch
   - Explain its built off the official images
   - Test before going to production
   - Link to the default config

- [x] **Changing settings in PHP**
   - Environment variable configurations
   - PHP ini
   - Disable all default configurations with `DISABLE_DEFAULT_CONFIG`

- [x] **Installing PHP additional PHP extensions**
   - Link to default PHP modules
   - Install PHP Redis
   - Install PHP Postgres
   - Installing your own
   - PECL Extensions

- [x] **Adding your own start up scripts**
    - Built-in automations with Laravel already
   - Understanding `docker-php-serversideup-entrypoint`
      - How it works
      - Numerical order
      - Must be in `/bin/sh`
   - Disabling our default configurations

- [x] **Configuring SSL**
   - Default behavior
   - How to enable SSL
   - Providing your own certificate

- [ ] **Using S6 Overlay**
   - Document host compatibility (related https://github.com/serversideup/docker-php/discussions/191)

- [x] **Migrating from v2 to v3**
   - New Features
   - Breaking Changes
   - Variable deprecations

### Reference
- [ ] **Custom binaries**
   - Official PHP binaries still included
       - docker-php-ext-configure
       - docker-php-ext-install
       - docker-php-ext-enable
       - docker-php-source
   -  docker-php-serversideup-dep-install-alpine
   - docker-php-serversideup-dep-install-debian
   - docker-php-serversideup-entrypoint
   - docker-php-serversideup-pecl-install
   - docker-php-serversideup-install-php-ext-installer
   </div>

**Comment by minkbear** [comment]
In the section "Example Docker Compose File" on https://release-v3-0.docker-php.pages.dev/docs/laravel/laravel-task-scheduler, I follow this line `command: ["su", "webuser", "-c", "php artisan schedule:work"]` then got the error no user webuser. I use `serversideup/php:beta-7.4-fpm-nginx` How to fix this?
