### ISSUE TITLE
Mirror containers to Github Container Registry

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#231]
### Discussed in https://github.com/serversideup/docker-php/discussions/218

<div type='discussions-op-text'>

<sup>Originally posted by **tomschlick** October 25, 2023</sup>
Now that you're working on the new version 3 beta, it might be a good time to start mirroring container images to the [Github Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry). 

While the images would be exactly the same as those pushed to DockerHub, some benifits include faster push/pull times for those of us using Github Actions, direct integration with the repo to show the containers, and additional redundancy in case DcokerHub [tightens the belt like they started to](https://www.docker.com/pricing/october-2022-pricing-change-faq/) with private repos last year. </div>

**Comment by jaydrogers** [comment]
Hey @tomschlick,

Great news! v3.0 will have our images published to **DockerHub & GitHub Packages** 🥳

<img width="870" alt="image" src="https://github.com/serversideup/docker-php/assets/3174134/0ca847b3-0512-4e16-bf41-6cd0d4374e66">

The betas are available on there now, but I am not officially calling the beta "released" yet. I have to finish up some documentation before I officially announce the availability of the beta.

### GitHub Packages URL
https://github.com/serversideup/docker-php/pkgs/container/php

Thanks for your feature suggestion! More coming soon 🚀

**Comment by tomschlick** [comment]
Awesome! Thanks!

**Comment by jaydrogers** [comment]
Adding a note that this is fully documented and ready for v3.0: https://release-v3-0.docker-php.pages.dev/docs/getting-started/installation
