### ISSUE TITLE
My PHP is not capitalized for some reason

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#241]
<img data-attr-bugflow-screenshot src="https://public-assets.bugflow.io/projects/5/bugs/836/1701704049-screenshot.png" />

## 🌎 URL
<a href="http://localhost:3000/open-source/docker-php/docs">http://localhost:3000/open-source/docker-php/docs<a>

## ⚡️ Reported By
Jay Rogers

## 🔎 More details

<strong>Browser: </strong>Firefox 120 (120.0)

<strong>Screen Resolution: </strong>834x1194

<strong>Viewport Dimensions: </strong>1302x1280

**Comment by danpastori** [comment]
This is a unique scenario.

If there is not an `<h1>` tag (`#`), the title is auto-generated from the file name. When auto-generated from the file name, the title is capitalized, but not uppercase.

Ensure you have an `<h1>` tag on your page and that will be the link title.

**Comment by jaydrogers** [comment]
But I have an H1 tag (but through Markdown). See line 6

https://github.com/serversideup/docker-php/blob/69526996d20398e689510227cd516752c3228d92/docs/content/docs/3.guide/1.migrating-from-official-php-images.md?plain=1#L1-L6

**Comment by danpastori** [comment]
Weird. Below is my dev. The one I tested didn't have an H1 tag and I fixed it. Attached is the screenshot. Could be due to the Nuxt 3.8 upgrade with newer Nuxt Content module.

![Image](https://github.com/serversideup/docker-php/assets/2365103/5ee8cf67-7e6b-4c27-a61c-b849cb7a1a5d)

**Comment by jaydrogers** [comment]
My reference is from the `v3.0` branch. This behavior could come from Nuxt 3.8 since the release branch is not updated yet.
