### ISSUE TITLE
Automatic OG image generation

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#247]
## Problem
- Every documentation page does not have a unique OG image

## Proposed solution
The following should be done to resolve this:

### Use "Nuxt SEO" to generate images
https://nuxtseo.com/og-image/getting-started/your-first-image

### Image template (from [Figma File](https://www.figma.com/file/WuVX7tgB46clFe3mXmNWcV/PHP-Docker-Website?type=design&node-id=633-1213&mode=design&t=OdU27P8QqXye2KV8-11))
![Image](https://github.com/serversideup/docker-php/assets/3174134/46646fad-e16e-4ca4-a95d-ef3db3bed9a1)

- [x] Have the text automatically generate based off the page contents

```markdown
---
head.title: 'Migrating from official PHP Docker images'
description: 'Learn how easy it is to move from the official PHP docker images to serversideup/php.'
layout: docs
---
```

##### Title (white text)
- [x] Pull from `head.title` (@danpastori: feel free to change this if there is a better spot)

##### Description
- [x] Pull from `description`

### Build Process
- [x] Generate each image on build
- [x] Ensure one page has one unique OG image

### Cache busting
- [ ] Ensure that when a title is changed, the cache gets "busted" to clear the original image

**Comment by danpastori** [comment]
@jaydrogers Scratch that above. We can access the title differently.

**Comment by danpastori** [comment]
I believe all the cache busting and caching is configured automatically: https://nuxtseo.com/og-image/guides/cache
