### ISSUE TITLE
Cloudflare 

### ISSUE THREAD

**Issue by szepeviktor** [serversideup/docker-php#25]
Many people think that Cloudflare will protect their web application.
Many people are happy that Cloudflare pays for their CDN bandwidth.
I think Cloudflare is a monster. Especially in their free plan. You loose control of many things.

I conclude Cloudflare is not for business. You should protect your web application, pay for a CDN, purchase an SSL certificate etc.

_business meaning you have at least 1 employee in full-time job_

Sub 1 employee "businesses" are actually fantasies: none of the above applies!

**Comment by szepeviktor** [comment]
How about keeping IP ranges up to date?
https://www.cloudflare.com/ips-v4
https://www.cloudflare.com/ips-v6

**Comment by jaydrogers** [comment]
Right now it is manual. I am signed up on their email list and they do a good job on letting people know their IPs are changing. Just made an update not too long ago. I will re-open this if we need the automation.
