### ISSUE TITLE
Favicon is not loading

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#251]
<img data-attr-bugflow-screenshot src="https://public-assets.bugflow.io/projects/5/bugs/842/1701806605-screenshot.png" />

## 🌎 URL
<a href="https://release-v3-0.docker-php.pages.dev/docs">https://release-v3-0.docker-php.pages.dev/docs<a>

## ⚡️ Reported By
Jay Rogers

## 🔎 More details

<strong>Browser: </strong>Firefox 120 (120.0)

<strong>Screen Resolution: </strong>1440x2560

<strong>Viewport Dimensions: </strong>1302x2560

**Comment by danpastori** [comment]
This should be fixed now.
