### ISSUE TITLE
Allow OPEN_BASEDIR to be set, but default it to empty

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#258]
https://github.com/serversideup/docker-php/blob/aa4ad4416cc9168a9baa265f0419a3fd0b53e622/src/common/usr/local/etc/php/php.ini#L318

**Comment by xolf** [comment]
Would be cool if this can be set in future. I receive a similar error with the [`readme/metrics`](https://packagist.org/packages/readme/metrics) package. 

`is_file(): open_basedir restriction in effect. File(/composer/config.json) is not within the allowed path(s): (/var/www/html:/dev/stdout:/tmp)`

**Comment by herpaderpaldent** [comment]
@xolf have you seen that this issue is about the pre-release v3 version? In v2 you can add the open_basedir paths. 

If you use `symfony/process` the reason for the error might be because of v6.4 of the mentioned package. Pin the version to 6.3.4 to get your app running again
