### ISSUE TITLE
Running `apt-*` command failed on the beta fpm images

### ISSUE THREAD

**Issue by tfirdaus** [serversideup/docker-php#265]
### Affected Docker Images

🤔  It seems to only happen on the `beta-*-fpm` image variants. Tested on:

- `serversideup/php:beta-7.4-fpm`
- `serversideup/php:beta-8.2-fpm`

### Current Behavior

It throws error when running `apt-get update` command .

```
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Err:1 http://deb.debian.org/debian bullseye InRelease
  Couldn't execute /usr/bin/apt-key to check /var/lib/apt/lists/partial/deb.debian.org_debian_dists_bullseye_InRelease
```

### Expected Behavior

Should be able to reach to deb repository without any issues and get the package lists:

```
Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main arm64 Packages [8685 kB]
Get:5 http://deb.debian.org/debian bookworm-updates/main arm64 Packages [12.5 kB]
Get:6 http://deb.debian.org/debian-security bookworm-security/main arm64 Packages [130 kB]
Fetched 9078 kB in 2s (4107 kB/s)
Reading package lists...
```

Tested this on `serversideup/php:beta-8.2` without the `-fpm`.

### Steps To Reproduce

😢 **Failed** 

```
docker run --rm serversideup/php:beta-8.2-fpm apt-get update
```

👍  **Good**  

```
docker run --rm serversideup/php:beta-8.2 apt-get update
```

### Host Operating System

macOS Ventura (13.5.2)

### Docker Version

```markdown
Docker version 24.0.7, build afdd53b
```

**Comment by jaydrogers** [comment]
Thanks for the detailed bug report!

I have no idea why, but this fixed it in https://github.com/serversideup/docker-php/commit/694ab283993e5b38fea47c277bf37158d3a9f2a4

```diff
- COPY --chmod=644 src/php-fpm.d/ /
+ COPY src/php-fpm.d/ /
```

I don't know why being explicit with `--chmod=644` would affect the apt update 😆

## Fix is deployed
Watch this job for latest. Should be available in about an hour: https://github.com/serversideup/docker-php/actions/runs/7358546911
