### ISSUE TITLE
Everyone needs speed - Redis

### ISSUE THREAD

**Issue by szepeviktor** [serversideup/docker-php#29]
An average WordPress installation will see 3× - 10× speedup with `OPcache.validate_timestamps = 0` and Redis object cache.

Reasons

1. No disk access on PHP execution
2. (almost) No Database access on PHP execution

Please consider adding Redis as default. (I do that)

**Comment by szepeviktor** [comment]
> I do that

WP core > `wp-redis` plugin's drop-in file > `redis` (PECL) PHP extension (igbinary as dependency) > Redis server

**Comment by jaydrogers** [comment]
Thanks for submitting this! I will loop back to this once I am ready to tackle it. I love this idea! I did add `php-redis` in 3a63ba1cbb80fd239610e1ffb043ce7f8d7d8558 (but I wouldn't call this "done" yet 😃)

**Comment by szepeviktor** [comment]
e.g. Redis server is not included :)

**Comment by jaydrogers** [comment]
The PHP-Redis library has been added, but I am going to suggest running Redis outside of the container. I might add more things later to document it, but it is right on the line of "being out of scope for PHP".
