### ISSUE TITLE
docker-php-serversideup-s6-init: not found

### ISSUE THREAD

**Issue by leonardyrj** [serversideup/docker-php#301]
### Affected Docker Images

FROM serversideup/php:8.2-fpm-nginx

### Docker Labels of the affected images

 => ERROR [3/3] RUN docker-php-serversideup-s6-init                                                                                                                                                                                0.2s
------
 > [3/3] RUN docker-php-serversideup-s6-init:
0.213 /bin/sh: 1: docker-php-serversideup-s6-init: not found
------
Dockerfile:8

### Current Behavior

I'm trying to create my own startup script

### Expected Behavior

run with the image successfully.

### Steps To Reproduce

FROM serversideup/php:8.2-fpm-nginx

LABEL authors="carvalho"

COPY --chmod=755 ./entrypoint.d /etc/entrypoint.d/

RUN docker-php-serversideup-s6-init

./entrypoint.d/99-copy-env
#!/bin/sh

cd /var/www/html/

if [ ! -f ".env" ]; then
    cp .env.example .env
fi

### Host Operating System

Ubuntu

### Docker Version

```markdown
Client: Docker Engine - Community
 Version:           25.0.4
 API version:       1.43 (downgraded from 1.44)
 Go version:        go1.21.8
 Git commit:        1a576c5
 Built:             Wed Mar  6 16:32:12 2024
 OS/Arch:           linux/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.25.0 (126437)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:32:16 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by jaydrogers** [comment]
Change to `serversideup/php:beta8.2-fpm-nginx`.

Sorry for the confusion. Should hopefully have that fixed soon

**Comment by reganjohnson** [comment]
Same issue on `serversideup/php:7.4-fpm-nginx`
