### ISSUE TITLE
Remove X-XSS-Protection header

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#31]
Thanks to [/u/Tontonsb](https://www.reddit.com/user/Tontonsb/) on Reddit for this. [See our discussion](https://www.reddit.com/r/laravel/comments/nwnion/productionready_laravel_docker_setup/h1br53f) why this issue was created.

# Problem
* XXS filtering is enabled, but it actually creates more harm than good

# Solution
* Remove these lines from the Nginx security policy: https://github.com/serversideup/docker-php/blob/7223a37cab76dee4a88bd3e62c7839b26563460b/php/8.0/fpm-nginx/etc/nginx/server-opts.d/security.conf#L8-L9

# Further reading
* Here's a list of browsers that don't implement it: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
* Here's the OWASP decision on removing it from suggestions: https://github.com/OWASP/CheatSheetSeries/issues/376#issuecomment-602663932

**From /u/Tontonsb:**
Now, why did the browsers remove the feature and why it was (and is) considered a vulnerability? Because it "protects" in a manner that the attacker can observe. Here's one of the attacks abusing it: https://portswigger.net/research/abusing-chromes-xss-auditor-to-steal-tokens

**Comment by jaydrogers** [comment]
@danpastori You should review this above. ☝️

I'll probably pull this in the next release if you are cool with it.

**Comment by jaydrogers** [comment]
We did, but then we removed it 😁

https://github.com/serversideup/docker-php/blob/7223a37cab76dee4a88bd3e62c7839b26563460b/php/8.0/fpm-nginx/etc/nginx/server-opts.d/security.conf#L17-L19

**Comment by danpastori** [comment]
Just thinking out loud. How hard would it be to add some sort of custom `.env` type file that gets compiled into docker that's set on a per-app basis? For example (I'll try my best at yml):
```
Headers
     CSP
          "default-src"
          'self'
          http:
```
And then you just flatten that array to be the header that gets added. I know when working with Electron and CapacitorJS, you have to have this down to a science.

**Comment by danpastori** [comment]
As an appending to ☝️, are there any other settings that would be useful to store in an env that are app specific? Maybe you already have this.

**Comment by jaydrogers** [comment]
Good news is, there is no YAML in this repo. 🤓

ENVs are set like this: https://github.com/serversideup/docker-php/blob/7223a37cab76dee4a88bd3e62c7839b26563460b/php/8.0/fpm-nginx/Dockerfile#L9-L19

So that means it would look like this:
```docker
ENV CONTENT_SECURITY_POLICY="\"default-src \'self\' http: https: data: blob: \'unsafe-inline\'\" always\;"
```
☝️ But as you can see, **I don't even know if this example will work.**

We would have to escape all of this stuff in bash, which might get really messy. Not sure how NGINX would take this.

Thoughts?

**Comment by danpastori** [comment]
I'm thinking about providing an optional "App Specific" env. Would that make sense? Some sort of config file that you could customize and build into the docker image to overwrite values, or add values on an app specific basis? 

It could be completely out of scope since I can set some of the CSP stuff in HTML. Just thinking.

**Comment by jaydrogers** [comment]
That could definitely work. The only negative I see from controlling it from the app level for the ENV would be we need to figure that out for both application types:

1. Laravel
2. WordPress

Putting the ENV at the docker layer will allow us to set an ENV within Docker which could then be easily customized for any type of app.

**Comment by jaydrogers** [comment]
I wonder if @szepeviktor would have any thoughts on this? ☝️

**Comment by szepeviktor** [comment]
![kép](https://user-images.githubusercontent.com/952007/121778407-0a67b100-cb97-11eb-8b89-5a3fc74681a5.png)

This speaks for itself. ~100% of browser makers do not support it.

I do not understand the technical details.
As far as I see security is made from [very many steps](https://github.com/szepeviktor/debian-server-tools/blob/master/webserver/WordPress-security.md). There is no way to protect a website without human 👨‍🔬 expertise and continuous presence: an expert webmaster.

**Comment by jaydrogers** [comment]
Thanks @szepeviktor!

Specifically, I was wondering if there is a sensible way to set the content security policy as an ENV without it looking like garbage with all of the escaping. See this comment for more details: https://github.com/serversideup/docker-php/issues/31#issuecomment-859757583

**Comment by szepeviktor** [comment]
```
ENV CONTENT_SECURITY_POLICY='{ "some": "JSON" }'
```

💡 Then use `jq` to turn it into a HTTP header.
