### ISSUE TITLE
Create a method to silence the initialization banner only

### ISSUE THREAD

**Issue by joshmanders** [serversideup/docker-php#317]
### Affected Docker Images

All of them.

### Current Behavior

When I start up my application I am met with this banner.

```
--------------------------------------------------------------------
 ____                             ____  _     _        _   _
/ ___|  ___ _ ____   _____ _ __  / ___|(_) __| | ___  | | | |_ __
\___ \ / _ \  __\ \ / / _ \  __| \___ \| |/ _` |/ _ \ | | | |  _ \
 ___) |  __/ |   \ V /  __/ |     ___) | | (_| |  __/ | |_| | |_) |
|____/ \___|_|    \_/ \___|_|    |____/|_|\__,_|\___|  \___/| .__/
                                                            |_|

Brought to you by serversideup.net
--------------------------------------------------------------------

🙌 To support Server Side Up projects visit:
https://serversideup.net/sponsor

-------------------------------------
ℹ️ Container Information
-------------------------------------

Docker user:   root
Docker uid:    0
Docker gid:    0
OPcache:       ✅ Enabled
```

Which is fine for default, but I should be able to silence it to reduce noise in my systems. Docs and repository code shows that I must set `LOG_OUTPUT_LEVEL` to `off` to silence this. But the docs also state this env var is used to set levels for other things such as nginx/apache/etc.

### Expected Behavior

I should be able to silence the unnecessary logging without silencing the logging I want.

### Steps To Reproduce

1. Use these images as intended

### Host Operating System

macOS/Linux

### Docker Version

```markdown
Docker version 25.0.3, build 4debf41
```

**Comment by jaydrogers** [comment]
Good point! I'll create a special env called `SILENCE_INIT_BANNER` that will affect the first initialization banner only

**Comment by jaydrogers** [comment]
Just added a variable called `SHOW_WELCOME_MESSAGE` and defaulted it to `true`.

You can easily set this to `false` if you want that message to go away.

### Tracking the deployment
- Will be made available on our [`serversideup/php-dev`](https://hub.docker.com/r/serversideup/php-dev) images once this build completes: https://github.com/serversideup/docker-php/actions/runs/8791631193
- It won't make it into our beta release until another beta release, but it might just move into "stable" with the pending v3.0 stable release (which is hopefully the next release 🤞)

I appreciate you contributing this idea!
