### ISSUE TITLE
New release of php versions breaks current spin setup

### ISSUE THREAD

**Issue by ps-20x** [serversideup/docker-php#320]
### Affected Docker Images

`serversideup/php:beta-8.3-fpm-nginx`
`serversideup/php:8.3-fpm-nginx-v2.2.1`

### Current Behavior

We are using the above mentioned php version. As There was a new version released we automatically get the beta version now for new builds. The migration guide says to add `-v2.2.1` to the php version but fails:
> failed to solve: serversideup/php:beta-8.3-fpm-nginx-v2.2.1: docker.io/serversideup/php:beta-8.3-fpm-nginx-v2.2.1: not found

### Expected Behavior

There should also be a `v2.2.1` version for the php8.3 beta

### Steps To Reproduce

1) Setup spin with php83 in a laravel project
2) run `spin --build`

### Host Operating System

MacOS 14.4

### Docker Version

```markdown
Client:
 Cloud integration: v1.0.35+desktop.13
 Version:           26.0.0
 API version:       1.44 (downgraded from 1.45)
 Go version:        go1.21.8
 Git commit:        2ae903e
 Built:             Wed Mar 20 15:14:46 2024
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.28.0 (139021)
 Engine:
  Version:          25.0.3
  API version:      1.44 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:       f417435
  Built:            Tue Feb  6 21:14:22 2024
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.28
  GitCommit:        ae07eda36dd25f8a1b98dfbf587313b99c0190bb
 runc:
  Version:          1.1.12
  GitCommit:        v1.1.12-0-g51d5e94
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by jaydrogers** [comment]
The `v2.2.1` is a "stable" release and is our Ubuntu based images.

The beta channel currently is our v3 images, which is expected to his stable soon after the "beta4" release.

I recommend subscribing to our releases: https://serversideup.net/open-source/docker-php/docs/getting-started/upgrade-guide#subscribe-to-repository-updates

See what needs to change for Beta4: https://github.com/serversideup/docker-php/releases/tag/v3.0.0-beta4
