### ISSUE TITLE
php artisan tinker: Writing to directory /var/www/.config/psysh is not allowed

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#326]
### Originally posted by @JanickOtten

_Originally posted by @JanickOtten in https://github.com/serversideup/spin/issues/76#issuecomment-2076492476_

Thanks for the fix! Just came across a minor issue when trying to run a Tinker session in development (using `docker exec -it <container> php artisan tinker`), where I'm receiving a permission error, causing the Tinker session to abort:

```
Writing to directory /var/www/.config/psysh is not allowed.

  at vendor/psy/psysh/src/ConfigPaths.php:327
    323▕             @\mkdir($dir, 0700, true);
    324▕         }
    325▕ 
    326▕         if (!\is_dir($dir) || !\is_writable($dir)) {
  ➜ 327▕             \trigger_error(\sprintf('Writing to directory %s is not allowed.', $dir), \E_USER_NOTICE);
    328▕ 
    329▕             return false;
    330▕         }
    331▕ 
```

I fixed this by chowning the `/var/www/` directory to www-data as well.

`RUN chown www-data:www-data /var/www`

In this https://github.com/serversideup/spin/issues/76#issuecomment-2074143365 I noticed ps-20x ran this as well.

**Comment by jaydrogers** [comment]
@janickotten & @ps-20x:

Thanks so much for the proposed fix for the `php artisan tinker` support. I just pushed this commit (https://github.com/serversideup/docker-php/commit/4bfcb0821e00935ac01b3cb81d84acf9a0b2ef78) to **serversideup/php** and it's building right now:

- https://github.com/serversideup/docker-php/actions/runs/8833737215

This takes about an hour to build, but these images will be made available on our **[serversideup/php-dev](https://hub.docker.com/r/serversideup/php-dev/tags)** repo for initial testing.

If you want to remove your workarounds in your Dockerfiles, then quickly try these images -- it should work without your extra lines of code. It worked on my end for my tests.

Be sure to switch the image back (don't use `serversideup/php-dev` forever) and [subscribe to the repo updates](https://serversideup.net/open-source/docker-php/docs/getting-started/upgrade-guide#subscribe-to-repository-updates) because if this fix works, it will be made available in the next beta release 👍

We're getting to the point were these images will be stable, so hopefully the release after that will be the v3.0 stable 🥳

**Comment by JanickOtten** [comment]
Thanks @jaydrogers, I can confirm this is fixed in `serversideup/php-dev`. Looking forward to the v3.0 stable release!
