### ISSUE TITLE
PRs fail because of Docker Logins are not set

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#339]
## Problem
- PRs fail because there are workflow dependencies for Docker logins to be configured 

## Examples
- https://github.com/serversideup/docker-php/actions/runs/8883052632/job/24389060092#step:4:1
- https://github.com/serversideup/docker-php/actions/runs/8883052629/job/24389080952#step:5:6

## Proposed Solution
- [ ] See if we can use GitHub packages only (instead of having people use a Dockerhub account)

**Comment by szepeviktor** [comment]
@jaydrogers There is a GHA context variable for that
```yaml
if: ${{ github.event_name == 'pull_request' && ! github.event.pull_request.head.repo.fork }}
```

**Comment by jaydrogers** [comment]
Thanks! I had something similar with that, but the problem I was running into was uploading to a registry dedicated for testing.

I don't want any possibility of giving away my production credentials and I attempted to even use GHA only, but that ran into permissions errors with the GHA token.

My other thought was to create a special user for DockerHub, but even with that, PRs don't have access to secrets -- meaning I would have to use unencrypted variables 😅

**Comment by szepeviktor** [comment]
No, PR-s from forks should simply not publish Docker images.

**Comment by szepeviktor** [comment]
Here is a how to dump a GHA context.
https://github.com/szepeviktor/byte-level-care/blob/master/.github/workflows/workflow.yml#L48-L63

There are a dozen of them.
https://docs.github.com/en/actions/learn-github-actions/contexts

**Comment by jaydrogers** [comment]
I was thinking of having it create an image then dump it to a tar as an artifact?

It would just be nice to have a single source of truth for me to collaborate with someone.

That's why I was thinking some separate repository with totally separate credentials.

**Comment by jaydrogers** [comment]
This has been fixed and GitHub Actions will only run if it is a PR from the main repository 👍
