### ISSUE TITLE
Adding custom script fails to start

### ISSUE THREAD

**Issue by WisdomSky** [serversideup/docker-php#351]
### Affected Docker Images

serversideup/php:8.3-fpm-nginx

### Current Behavior

`RUN docker-php-serversideup-s6-init` returns permission denied

### Expected Behavior

The custom dockerfile should execute without problems as documented here: https://serversideup.net/open-source/docker-php/docs/customizing-the-image/adding-your-own-start-up-scripts#docker-php-serversideup-s6-init-usage

![image](https://github.com/serversideup/docker-php/assets/6792172/75a01ad6-9550-497e-8259-1b9f8926c6fc)

![image](https://github.com/serversideup/docker-php/assets/6792172/028f9c1a-3be6-444a-9c91-02883730280e)

### Steps To Reproduce

1. Create `entrypoint.d` directory
2. Inside the `entrypoint.d` directory, create a custom shellscript e.g `99-custom.sh`
3. Create custom Dockerfile as shown in the [docs](https://serversideup.net/open-source/docker-php/docs/customizing-the-image/adding-your-own-start-up-scripts#docker-php-serversideup-s6-init-usage) then save.
4. Update docker-compose file as shown [here](https://serversideup.net/open-source/docker-php/docs/customizing-the-image/adding-your-own-start-up-scripts#example-create-a-custom-entrypoint-script).
5. Run docker compose up

### Host Operating System

Debian 11

### Docker Version

```markdown
Docker version 26.1.0, build 9714adc
```

**Comment by jaydrogers** [comment]
Thanks for pointing this out!

The docs were dated and it was missing the correct permissions.

New example:

```dockerfile
FROM serversideup/php:8.3-fpm-nginx

ENV S6_CMD_WAIT_FOR_SERVICES=1

COPY --chmod=755 ./entrypoint.d/ /etc/entrypoint.d/

# Change to root, so we can do root things
USER root

# As root, run the docker-php-serversideup-s6-init script
RUN docker-php-serversideup-s6-init

# Change back to the www-data user
USER www-data
```

**Comment by WisdomSky** [comment]
@jaydrogers Thank you for the very quick response! I really appreciated it!

Can confirm that it now works as expected.

Thank you!
