### ISSUE TITLE
gRPC can't be found anymore!

### ISSUE THREAD

**Issue by pablojoii** [serversideup/docker-php#354]
### Affected Docker Images

Up to 2.2.1 we can apt install grpc for 8.1. Now it says package can't be found so we are stuck on 2.2.1 of 8.1-fpm-nginx

### Docker Labels of the affected images

Any over 8.1-fpm-nginx-v2.2.1

### Current Behavior

FROM serversideup/php:8.1-fpm-nginx-v2.2.1

RUN apt-get update \
    && apt-get install -y --no-install-recommends php8.1-grpc \ #THIS DOESN'T WORK ANYMORE
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

### Expected Behavior

To work :D 

## Failed build:

FROM serversideup/php:8.1-fpm-nginx 

RUN apt-get update \
    && apt-get install -y --no-install-recommends php8.1-grpc \ #THIS DOESN'T WORK ANYMORE
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
...

## Working build:

FROM serversideup/php:8.1-fpm-nginx-v2.2.1 

RUN apt-get update \
    && apt-get install -y --no-install-recommends php8.1-grpc \ #THIS DOESN'T WORK ANYMORE
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

### Host Operating System

Mac, Linux, Windows...

### Docker Version

```markdown
Any version as the package is reported as missing (why, we can't understand)
```

**Comment by jaydrogers** [comment]
V3 had massive upgrades. We've been working on this for a while and have had a number of beta releases before the stable release.

Learn how to migrate to the new version: https://serversideup.net/open-source/docker-php/docs/guide/migrating-from-v2-to-v3

It's also a great idea to subscribe to the releases https://serversideup.net/open-source/docker-php/docs/getting-started/upgrade-guide#subscribe-to-repository-updates
