### ISSUE TITLE
mkdir() "/var/lib/nginx/body" failed (13: Permission denied)

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#358]
# Discord Report
<img width="1156" alt="image" src="https://github.com/serversideup/docker-php/assets/3174134/5149ba9b-b86e-4d87-a6ca-ff7a40b61110">

### Link to Discord
https://discord.com/channels/910287105714954251/1238858705114763316

**Comment by jaydrogers** [comment]
A fix has been pushed up -- monitoring this job for a development release, then will push to stable:

https://github.com/serversideup/docker-php/actions/runs/9053441412

**Comment by jaydrogers** [comment]
This seems to be fixed now.

In reality, no code changes were made. I think it was a package dependency during build that got messed up and has now been reverted.

Regardless, I am pushing up a release to trigger a rebuild to fix this.

**Comment by omerkoseoglu** [comment]
Thanks, problem solved 🥳
