### ISSUE TITLE
PHP unit ignores PHP_UPLOAD_MAX_FILE_SIZE

### ISSUE THREAD

**Issue by lenvanessen** [serversideup/docker-php#394]
### Steps To Reproduce

1. Build a container using the serversideup/php:8.2-unit 
2. create a script with a phpinfo(); dump
3. upload_max_filesize is unset

#### What did you expect?
For upload_max_filesize to be set to the 100m default
#### What happened instead?
upload_max_filesize is undefined

### Affected Docker Images

- All images

**Comment by jaydrogers** [comment]
Thanks for pointing this out! I accidentally had `PHP_UPLOAD_MAX_FILESIZE`instead of `PHP_UPLOAD_MAX_FILE_SIZE` in the PHP ini.

It worked in PHP-FPM (only on web) because it was set correctly in the FPM config. This will be fixed in v3.3.0. Thanks for your help!
