### ISSUE TITLE
`install-php-extensions` from 8.3-fpm-nginx-alpine results in "permission denied" error

### ISSUE THREAD

**Issue by alexjustesen** [serversideup/docker-php#403]
### Steps To Reproduce

1. Using the Dockerfile below try to install additional php extensions using `install-php-extensions`
2. See error

```Dockerfile
FROM serversideup/php:8.3-fpm-nginx-alpine

# Switch to root so we can do root things
USER root

# Install additional extensions with root permissions
RUN install-php-extensions gd
```

#### What did you expect?

`gd` extension to successfully install.

#### What happened instead?

Received the following error:

```
 => ERROR [base 4/5] RUN install-php-extensions gd                                                                                                         3.1s
0.307 install-php-extensions v.2.2.14                                                                                                                           
0.307 #StandWithUkraine                                                                                                                                         
2.044 Updating channel "pecl.php.net"                                                                                                                           
2.159 Channel "pecl.php.net" is up to date                                                                                                                      
2.176 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
2.345 283BEBC4947F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091:
2.348 WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.20/main: Permission denied
2.348 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
2.420 283BEBC4947F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091:
2.421 WARNING: updating and opening https://dl-cdn.alpinelinux.org/alpine/v3.20/community: Permission denied
2.421 4 unavailable, 0 stale; 58 distinct packages available
```

### Affected Docker Images

serversideup/8.3-fpm-nginx-alpine

**Comment by alexjustesen** [comment]
Something I found in my research is that maybe the repo references should be `HTTP` instead of `HTTPS`.

https://github.com/alpinelinux/docker-alpine/issues/98#issuecomment-679267074

**Comment by jaydrogers** [comment]
Weird, can you try again? It seems like a temporary issue or a network error.

I just ran it on my machine and it worked:

![Screenshot 2024-07-17 at 11 26 59@2x](https://github.com/user-attachments/assets/bb49f6e8-92eb-4e32-97a1-a3d50c5b52ce)


### Alternative image to test
Could you try it with the beta image too?

```
serversideup/php:beta-8.3-fpm-nginx-alpine
```

### Make sure your images are up to date
Be sure you're running `docker pull` to get the latest updates:

```bash
docker pull serversideup/php:beta-8.3-fpm-nginx-alpine
docker pull serversideup/php:8.3-fpm-nginx-alpine
```

**Comment by alexjustesen** [comment]
Maybe I got hit by the firewall on this one, its odd that it worked with the Debian based images though.

**Comment by jaydrogers** [comment]
Could very well be!

Are you able to access these links in your browser?

- https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
-  https://dl-cdn.alpinelinux.org/alpine/v3.20/community

**Comment by alexjustesen** [comment]
Yeah so I guess that rules out the firewall... I don't have a clue why but updating the repo url to `http` worked for me (ref: https://github.com/alpinelinux/docker-alpine/issues/98#issuecomment-679278499).

```Dockerfile
RUN sed -i 's/https/http/' /etc/apk/repositories

# Install additional extensions with root permissions
RUN install-php-extensions gd
```

Hopefully this helps someone else should they run into the issue. Maybe an add for the docs in case someone gets the error?

**Comment by jaydrogers** [comment]
It's because of a certificate trust issue:

```
283BEBC4947F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091
```

Not sure why it would be happening for you and not me because the certificate chains should be the same since they are stored in the container.

Mine worked fine over HTTPS 🤷‍♂️

Keep me posted if the issue goes away if you try it on another network, server, etc.

**Comment by alexjustesen** [comment]
> Keep me posted if the issue goes away if you try it on another network, server, etc.

Will do, I'm going to try this off-network later today as well.

**Comment by vasilvestre** [comment]
I also had this issue on another image, my issue was with gitlab runner running docker 20.x and using 27.x worked for me. May be a docker version related issue
