### ISSUE TITLE
composer update / install not working

### ISSUE THREAD

**Issue by zigazajc007** [serversideup/docker-php#411]
### Steps To Reproduce

1. Try to build docker image from this Dockerfile:

```dockerfile
FROM serversideup/php:8.3-unit-v3.3.0

USER 33:33
WORKDIR /var/www/html

# Copy files to docker container
COPY --chown=33:33 src/ /var/www/html/public/
COPY --chown=33:33 composer.json /var/www/html/

RUN chmod 755 -R /var/www/html

# Install dependiencies from composer
RUN composer update --no-cache --no-dev --no-scripts --no-autoloader --ansi --no-interaction
```

Only important thing here is the image `serversideup/php:8.3-unit-v3.3.0` and the `RUN composer update` command.

#### What did you expect?
For composer to install all the dependencies.

#### What happened instead?
<img width="1340" alt="image" src="https://github.com/user-attachments/assets/92f8f57a-e9af-45b1-8eb6-cac0adc56c8d">

It kinda seems that composer can't connect to the Internet when trying to download dependencies?

### Affected Docker Images

serversideup/php:8.3-unit-v3.3.0

### Anything else?

The same problem seems to be present in `unit:1.32.1-php8.3` image as well.

**Comment by zigazajc007** [comment]
Note that composer successfully install all the dependencies when you manually execute the same command inside the container.

**Comment by zigazajc007** [comment]
Used `composer.json` file:
```json
{
	"require": {
		"paragonie/constant_time_encoding": "^2",
		"pragmarx/google2fa": "v8.0.1",
		"phpmailer/phpmailer": "^6.9",
		"devcoder-xyz/php-dotenv": "^2.1"
	}
}
```

**Comment by sqlldev** [comment]
Did you try to add this to Dockerfile?
`RUN apt update && apt install git -y`

**Comment by zigazajc007** [comment]
git is only used as a fallback when it fails to fetch code from composer. Fetching from composer seems to have a limit of 15 seconds, if it can't download code in 15 seconds than it fallbacks to git. When cloning project from git it doesn't seems to have a time limit, but if you look at the time you will see that it took 147.5 seconds total just to download 4 small libraries.

<img width="1277" alt="image" src="https://github.com/user-attachments/assets/bef2b6cd-fd37-4b10-b968-df9c6c549a95">

It seems that the problem is more of a really slow internet inside docker when building the image.

**Comment by zigazajc007** [comment]
When the image is built and container deployed, executing the same command inside the container tooks less than 10 seconds to download all the libraries. And it doesn't fallback to git.

<img width="892" alt="image" src="https://github.com/user-attachments/assets/93845ede-038c-4cd5-b455-cf317fbe45bf">

**Comment by jaydrogers** [comment]
Just checking in... Is this issue still happening?

I've done a ton of other work with `composer install` and I haven't seen this error come up.

Unfortunately I am not able to replicate this issue at all yet.

**Comment by jaydrogers** [comment]
Closing this for now, but I will re-open if we can get this to replicate 👍
