### ISSUE TITLE
Mistakes in Unit configuration

### ISSUE THREAD

**Issue by TheAndrey** [serversideup/docker-php#412]
### Steps To Reproduce

Hi,
I decided to build my application image based on Nginx Unit. I am having difficulty applying the custom server configuration due to errors found in the scripts.

### Outcome

1. Disabling logging of healthcheck does not work. Although there is a [rule in the configuration](https://github.com/serversideup/docker-php/blob/5878f654842ded04577819226e0e1722120ef4c0/src/variations/unit/etc/unit/config.d/ssl-off.json.template#L70), it is always [overwritten by the script](https://github.com/serversideup/docker-php/blob/5878f654842ded04577819226e0e1722120ef4c0/src/variations/unit/etc/entrypoint.d/10-init-unit.sh#L132-L133). Custom additional configs cannot affect this. You should delete the specified line in the initialization script.

2. Private [IP address ranges](https://github.com/serversideup/docker-php/blob/5878f654842ded04577819226e0e1722120ef4c0/src/variations/unit/etc/unit/config.d/ssl-off.json.template#L9-L30) are missing in the reverse proxy configuration, although [they are specified](https://github.com/serversideup/docker-php/blob/5878f654842ded04577819226e0e1722120ef4c0/src/variations/fpm-nginx/etc/nginx/server-opts.d/remoteip.conf#L5-L8) in Nginx. I want to use Unit as an application server located behind the upstream Nginx on the host.

3. [The current configuration](https://github.com/serversideup/docker-php/blob/5878f654842ded04577819226e0e1722120ef4c0/src/variations/unit/etc/unit/config.d/ssl-off.json.template#L45-L47) is very crude. I had to completely rewrite the config. In this case, it only works index.php at the same time, all other php scripts are downloaded as regular files. index.php you can also download it if you specify its name in the URL.

I got something like this configuration with my fixes.

```json
{

  "listeners": {
    "*:8080": {
      "pass": "routes",
      "forwarded": {
        "client_ip": "X-Forwarded-For",
        "protocol": "X-Forwarded-Proto",
        "recursive": false,
        "source": [
          "172.16.0.0/12"
        ]
      }
    }
  },

  "routes": [
    {
      "match": {
        "uri": "/healthcheck"
      },
      "action": {
        "return": 200
      }
    },
    {
      "match": {
        "uri": [
          "/",
          "*.php",
          "*.php/*"
        ]
      },
      "action": {
        "pass": "applications/php/direct"
      }
    },
    {
      "action": {
        "share": "/var/www/html/public$uri",
        "fallback": {
          "pass": "applications/php/index"
        }
      }
    }
  ],

  "applications": {
    "php": {
      "type": "php",
      "processes": {
        "max": 5,
        "spare": 1,
        "idle_timeout": 30
      },
      "targets": {
        "index": {
          "root": "/var/www/html/public/",
          "script": "index.php"
        },
        "direct": {
          "root": "/var/www/html/public/",
          "index": "index.php"
        }
      }
    }
  }

}
```

It is imperfect. index.php it does not start when going to the directory, unless you explicitly specify the URI in the config.

### Affected Docker Images

* serversideup/php:7.4-unit

**Comment by jaydrogers** [comment]
Thanks for opening this up! Yes, this was the first Unit configuration that I wrote and I am still learning.

I'd be glad to take on a PR if you have more experience. I'd like it to replicate the features of the `fpm-nginx` as much as possible.

**Comment by TheAndrey** [comment]
I'm also getting to know Unit for now. I solved problems by studying the documentation. I'm still working on the config. On your part, you need to finalize the configuration scripts.

Next problem. Any scripts located in `/etc/unit/config.d` [completely overwrite](https://github.com/serversideup/docker-php/blob/5878f654842ded04577819226e0e1722120ef4c0/src/variations/unit/etc/entrypoint.d/10-init-unit.sh#L121-L125) the Unit configuration. To avoid this, we need to be able to specify the URI where the configuration file will be downloaded, as [described in the documentation](https://unit.nginx.org/controlapi/#examples).

I still don't understand why SSL support and Cloudflare IP processing are needed, if this should be handled by a upstream server. This only complicates the configuration. The task of the application server is only route processing.

**Comment by jaydrogers** [comment]
> I still don't understand why SSL support and Cloudflare IP processing are needed, if this should be handled by a upstream server.

We can't always assume this, so that's why we have this included.

Keep me posted on what you learn and I'd love to review any suggestions for improvement.

**Comment by jaydrogers** [comment]
Thanks again for your report @TheAndrey!

I am working on v3.4 and I am breaking your suggestions into different tasks. Here is where everything at:

- https://github.com/serversideup/docker-php/issues/448
- https://github.com/serversideup/docker-php/issues/449
- https://github.com/serversideup/docker-php/issues/450
- https://github.com/serversideup/docker-php/issues/451

I will update each issue individually and close this one. I appreciate your feedback!
