### ISSUE TITLE
504 Gateway Timeout appears after 60 seconds even though PHP_MAX_EXECUTION_TIME is set

### ISSUE THREAD

**Issue by Hackbard** [serversideup/docker-php#424]
### Steps To Reproduce

i have some Request that will take time. Over a Minute.
But after 60 Seconds i become an 504 Gateway Timeout.

My Dockerfile:
```
FROM serversideup/php:8.2-fpm-nginx

ARG ENVIRONMENT=prod
ENV PUID=33
ENV PGID=33
ENV PHP_MEMORY_LIMIT=5120M
ENV SSL_MODE=off
ENV PHP_OPCACHE_ENABLE=1
ENV PHP_OPCACHE_MEMORY_CONSUMPTION=215
ENV PHP_OPEN_BASEDIR=/var/www/html:/tmp
ENV PHP_MAX_EXECUTION_TIME=360

# Adding files and configs nothing with server config
[...]
```

So i think nginx will terminate the connection with his default timeouts.

#### What did you expect?
i expected no Timeout or a config parameter

#### What happened instead?
i got an Timeout

### Affected Docker Images

serversideup/php:8.2-fpm-nginx

### Anything else?

/etc/nginx/nginx.conf
keepalive_timeout 65

**Comment by jaydrogers** [comment]
This is what ClaudeAI suggested, let me give this a whirl and I will get back 👍

```php
<?php
set_time_limit(360); // Set PHP execution time limit to 360 seconds

header('Content-Type: text/plain');

echo "Script started at: " . date('Y-m-d H:i:s') . "\n";

// Simulate a long-running process
for ($i = 1; $i <= 70; $i++) {
    echo "Second $i\n";
    flush();
    ob_flush();
    sleep(1);
}

echo "Script completed at: " . date('Y-m-d H:i:s') . "\n";
?>
```

**Comment by draude** [comment]
Don't know if that helps, but let's share some knowledge: I've been into this kind of problem more than once (no way to learn...). 
A PHP Script can keep executing even NGINX closes connection, like SQL can keep executing a query even the PHP script finishes.
If `PHP_MAX_EXECUTION_TIME` does not change NGINX timeout, the connection will close and the script will continue till getting to the max execution time when needed.
Also sometimes the execution time for a PHP script is not related to NGINX timeout because the script is not sending response to the client.

**Comment by Hackbard** [comment]
Exactly. But i need the Answer ;)

And thats is the keepalive_timeout config param i think in nginx.

**Comment by draude** [comment]
The one you mention is inside http section, 
I think for NGINX with FPM the way is chaging in sever section for sure the first one and don't really know wether the others are always needed:
```
fastcgi_read_timeout X;
fastcgi_connect_timeout X;
fastcgi_send_timeout X;

```

**Comment by jaydrogers** [comment]
Thanks for chiming in fellas!

So I am thinking we might need to add a variable here?

We could do a single variable of `NGINX_FASTCGI_TIMEOUT` and set all three of those values to the same? Or should we do three variables for full control?

**Comment by Hackbard** [comment]
In my opinion we can go with 1 Variabel.

**Comment by jaydrogers** [comment]
# ✅ This should be fixed
Thanks for chiming in @Hackbard and @draude!

### Here's what I did
- @draude was correct, setting `keepalive_timeout` had no effect. I believe this is the HTTP timeout
- Instead, I set `fastcgi_read_timeout` to whatever PHP_MAX_EXECUTION_TIME is set to

You can see my results here:

![Image](https://github.com/user-attachments/assets/306e2221-9d72-4c63-b2ea-dc03297e6617)

# 🚀 When this will be available
You can test this once the build is complete on v3.4:

- https://github.com/serversideup/docker-php/pull/445

I appreciate your help on this!
