### ISSUE TITLE
Improve docker-php-serversideup-set-id

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#430]
I ran into the same problem with images where the s6 overlay is present.

The problem is that changing the ID of an existing user using `docker-php-serversideup-set-id` is a ugly hack. After changing the ID, you need to update all user rights to files and directories in order to overwrite the previous UID/GID stored in the file system. For this reason, in order for access to files from the container and the host to work on both sides, it is enough that the UID and GID match, the names of users and groups may differ.

> I am still confused on what is causing this error and why running chown -R www-data:www-data /run fixes it.

This updates the user ID to the current ones. You need to use `ls` with the `-n` flag to see the ID instead of the user's display name.

The script `docker-php-serversideup-set-id` can be improved by replacing the old ID with a new one throughout the file system (ex. `find / -uid $OLD_ID -gid $OLD_ID`). Then there will be no need for script `docker-php-serversideup-set-file-permissions`.

_Originally posted by @TheAndrey in https://github.com/serversideup/docker-php/issues/376#issuecomment-2293534307_

**Comment by jaydrogers** [comment]
Thanks for the suggestion @TheAndrey. You're right -- it was an ugly hack. I don't know what I was thinking at the time 😆

I am working to improve this now 👍

**Comment by jaydrogers** [comment]
I think I know why I created that script. It's because I can't always assume that `www-data` originally owns the directories I need to update.

See these errors after using the `find` command:

<img width="1075" alt="image" src="https://github.com/user-attachments/assets/4d93394a-5cbc-4abf-96f7-3969919a3bb8">

These errors appear because some of these directories are owned by `nginx` (not `www-data`). If we want templating to work with ENV vars, I need a list of directories to run with `www-data`.

I would agree that `docker-php-serversideup-set-file-permissions` could possibly be improved (and possibly even merged into `docker-php-serversideup-set-id`) but for now I feel there are bigger optimizations to make before completing this.

I am going to close this for now, but will re-open if we need to pursue it in the future

**Comment by TheAndrey** [comment]
I was unable to adapt your images for use in production. I don't like the idea of configuration via environment variables. This is difficult and does not give you the full freedom that installing your own configuration file.

With your settings, the application can also change the software configuration files, which in fact should not be.

Configurations should be created as root, then you can run application processes on behalf of another user with reduced permissions, as it happens on a real machine.

**Comment by jaydrogers** [comment]
We offer both options where you can use environment variables (by default) or bring your own config. Just set `DISABLE_DEFAULT_CONFIG` and you can mount your own configs easily: https://serversideup.net/open-source/docker-php/docs/reference/environment-variable-specification
