### ISSUE TITLE
The image serversideup/php:8.3-unit is vastly larger than documented at 782MB

### ISSUE THREAD

**Issue by hookenz** [serversideup/docker-php#431]
### Steps To Reproduce

1. `docker pull serversideup/php:8.3-unit`
2. docker images | grep serversideup

#### What did you expect?
A much smaller image around 300+MB with my additions

#### What happened instead?
An enormous image of 900+MB with my additions

### Affected Docker Images

serversideup/php:8.3-unit

**Comment by hookenz** [comment]
It looks like dockerhub displays a compressed image size while docker images displays the uncompressed size. 
I'm happy for this to be closed.

**Comment by jaydrogers** [comment]
Thanks for the update! My heart skipped a few beats reading the title 😅
