### ISSUE TITLE
Improve GitHub Actions runners

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#440]
# Problem
- We're limited to 20 concurrent runs with GitHub Actions

# Proposed solution
- Run self-hosted runners on AWS with https://runs-on.com

**Comment by crohr** [comment]
@jaydrogers Thanks for trying RunsOn, let me know if you need any support!

**Comment by jaydrogers** [comment]
You rock @crohr! I am totally digging my experience with RunsOn.

I'm excited to see how this turns out for this project. It could be a huge time saver to maintaining these open source images 👍
