### ISSUE TITLE
Unit: Disabling logging of healthcheck does not work.

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#448]
### Steps To Reproduce

1. Run `docker run --rm -v $(pwd):/var/www/html/public serversideup/php:8.3-unit-bookworm`
2. You'll see the health checks in the access log

#### What did you expect?
- Access log should not appear

#### What happened instead?
- Access log to the health check is appearing

### Affected Docker Images

Unit images only

### Anything else?

Originally reported by @TheAndrey in https://github.com/serversideup/docker-php/issues/412:

> Disabling logging of healthcheck does not work. Although there is a [rule in the configuration](https://github.com/serversideup/docker-php/blob/5878f654842ded04577819226e0e1722120ef4c0/src/variations/unit/etc/unit/config.d/ssl-off.json.template#L70), it is always [overwritten by the script](https://github.com/serversideup/docker-php/blob/5878f654842ded04577819226e0e1722120ef4c0/src/variations/unit/etc/entrypoint.d/10-init-unit.sh#L132-L133). Custom additional configs cannot affect this. You should delete the specified line in the initialization script.

**Comment by hookenz** [comment]
Thankyou! I was about to report this bug.   I can remove my workaround.

**Comment by jaydrogers** [comment]
The beta images should be pretty stable if you want to use those now.

I'm hoping to have them merged to stable next week.
