### ISSUE TITLE
Unit: Configuration only works with index.php

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#450]
### Steps To Reproduce

TBD

#### What did you expect?
- All PHP files should be processed as PHP

#### What happened instead?
- PHP files are being downloaded

### Affected Docker Images

Unit images only

### Anything else?

Originally reported by @TheAndrey in https://github.com/serversideup/docker-php/issues/412:

> [The current configuration](https://github.com/serversideup/docker-php/blob/5878f654842ded04577819226e0e1722120ef4c0/src/variations/unit/etc/unit/config.d/ssl-off.json.template#L45-L47) is very crude. I had to completely rewrite the config. In this case, it only works index.php at the same time, all other php scripts are downloaded as regular files. index.php you can also download it if you specify its name in the URL.
> 
> I got something like this configuration with my fixes.
> 
> ```json
> {
> 
>   "listeners": {
>     "*:8080": {
>       "pass": "routes",
>       "forwarded": {
>         "client_ip": "X-Forwarded-For",
>         "protocol": "X-Forwarded-Proto",
>         "recursive": false,
>         "source": [
>           "172.16.0.0/12"
>         ]
>       }
>     }
>   },
> 
>   "routes": [
>     {
>       "match": {
>         "uri": "/healthcheck"
>       },
>       "action": {
>         "return": 200
>       }
>     },
>     {
>       "match": {
>         "uri": [
>           "/",
>           "*.php",
>           "*.php/*"
>         ]
>       },
>       "action": {
>         "pass": "applications/php/direct"
>       }
>     },
>     {
>       "action": {
>         "share": "/var/www/html/public$uri",
>         "fallback": {
>           "pass": "applications/php/index"
>         }
>       }
>     }
>   ],
> 
>   "applications": {
>     "php": {
>       "type": "php",
>       "processes": {
>         "max": 5,
>         "spare": 1,
>         "idle_timeout": 30
>       },
>       "targets": {
>         "index": {
>           "root": "/var/www/html/public/",
>           "script": "index.php"
>         },
>         "direct": {
>           "root": "/var/www/html/public/",
>           "index": "index.php"
>         }
>       }
>     }
>   }
> 
> }
> ```
> 
> It is imperfect. index.php it does not start when going to the directory, unless you explicitly specify the URI in the config.

**Comment by jaydrogers** [comment]
I am able to replicate this, but I am equally as confused by this. I tried doing this:

```json
      "match": {
        "uri": [
          "/",
          "*.php",
          "*.php/*"
        ]
      },
```

But that had the same results.

I might circle back to this one later. I really want to get v3.4 out the door and I would gladly take a PR to resolve this in a near release.

**Comment by jpangborn** [comment]
I'm happy to spend some time working on the Unit configuration. I am using it in production. Any requirements for the configuration? It may be difficult to create a configuration that both allows the execution of arbitrary php files and handles funneling URIs to the index.php, but I make an attempt at it.

**Comment by jpangborn** [comment]
Added a PR to address this: #458

**Comment by jaydrogers** [comment]
Thanks for your contributions! I love seeing your content about serversideup/php.

I did some testing and ran into some small issues. Documented them here: https://github.com/serversideup/docker-php/pull/458#issuecomment-2414798161

I might circle back to this on v3.5. I appreciate your help!

**Comment by jpangborn** [comment]
Updated the PR.
