### ISSUE TITLE
Nginx performance directives break Livewire

### ISSUE THREAD

**Issue by dakira** [serversideup/docker-php#46]
The order in which nginx location directives are evaluated leads to this

https://github.com/serversideup/docker-php/blob/4233993f7367c3fd39789a5826917bdfd12b4436/templates/fpm-nginx/etc/nginx/server-opts.d/performance.conf#L13-L17

being evaluated before this

https://github.com/serversideup/docker-php/blob/4233993f7367c3fd39789a5826917bdfd12b4436/templates/fpm-nginx/etc/nginx/sites-available/default#L32-L41

This makes it impossible to define Laravel routes like `livewire/livewire.js` because they will always be seen as static assets. Same problem if the Laravel app servers other assets through its own routing.

**Comment by jaydrogers** [comment]
Thanks for posting this!

Do you have steps that I can follow to replicate this? I will be sure to evaluate and get this fixed 👍

**Comment by jaydrogers** [comment]
Also adding, best template for me to resolve bugs is:

```
## Issue description
<!-- Replace this comment with a short explanation of what is going on -->

## Environment

- Opertaing System Version:
- Docker Version:

## Steps to reproduce the issue

1.  
2.  
3.  

## What is expected?
<!-- Give us an explanation of what should be happening -->

## Additional details / screenshots
<!-- Screenshots, console output, logs, etc are extremely helpful -->
```

**Comment by shinsenter** [comment]
@dakira 
I understand your issue.

## Issue description


## Environment

- Opertaing System Version:
- Docker Version:

## Steps to reproduce the issue

1.  Create a route in Laravel call "test.js", then print "Hello World!"
```php
Route::get('test.js', function () {
    return 'Hello World';
});
```
2.  Access http://localhost/test.js

## What is expected?
HTTP 200 response with a text: Hello World!

## Additional details / screenshots
Received HTTP 404 Not found, because Nginx directive for static file is evaluated first.

**Comment by shinsenter** [comment]
@jaydrogers 

I appreciate you giving these projects away for free (and hope it stays free for future maintenance). I'm also digging into the components of your projects, to make sure they are transparent, secure and performant enough for the projects I'm working on.

**Comment by jaydrogers** [comment]
Thanks!! We love contributing to open source and our goal is to continue to make it free.

We just launched a sponsorship program for those interested (https://github.com/sponsors/serversideup), but no pressure on signing up. We haven't really promoted it yet.

We're hoping to gain a lot of momentum where we can and build up a solid financial base where we can release even more open source projects. Lots of things in the works! 🚀

**Comment by jaydrogers** [comment]
Thanks for this! I will review and get back on this soon.

**Comment by shinsenter** [comment]
@jaydrogers 

https://github.com/serversideup/docker-php/blob/4233993f7367c3fd39789a5826917bdfd12b4436/templates/fpm-nginx/etc/nginx/server-opts.d/performance.conf#L16
Not tested, but I believe adding this after the 16th line may fix it.


```nginx
try_files $uri /index.php?$query_string; 
```

This will tell nginx to try the index.php when requested asset does not exists.

**Comment by jaydrogers** [comment]
I opened a PR #51.

It seems like it is working well for me based on the test provided.

Can you guys try a beta image and see if it works for you? https://hub.docker.com/r/serversideup/php/tags?name=beta&page=1&ordering=-name

**Comment by dakira** [comment]
@jaydrogers Hey. I can confirm the beta fixes this for me.

**Comment by jaydrogers** [comment]
Just merged this, thanks all! 🥳
