### ISSUE TITLE
Removing the default .ini file causes Permission denied when docker build

### ISSUE THREAD

**Issue by LAGGOUNE-Walid** [serversideup/docker-php#461]
### Steps To Reproduce

1. Create my own php.ini file 
2. Create Docker file like mentioned here https://serversideup.net/open-source/docker-php/docs/customizing-the-image/changing-common-php-settings#setting-your-own-phpini 
3. run docker build 

#### What did you expect?
Successful build excepted
#### What happened instead?
Failed build due to permission denied

### Affected Docker Images

serversideup/php:8.3-fpm-nginx

### Anything else?

```
from serversideup/php:8.3-fpm-nginx
RUN rm /usr/local/etc/php/conf.d/serversideup-docker-php.ini
COPY php.ini /usr/local/etc/php/conf.d/
```

**Comment by YevheniiVolosiuk** [comment]
In your dockerfile first do run and copy in root user after operation change to unprivileged user. Tested it works.

```
FROM serversideup/php:8.3-fpm-nginx

USER root

RUN rm /usr/local/etc/php/conf.d/serversideup-docker-php.ini

COPY php.ini /usr/local/etc/php/conf.d/

USER www-data
```

**Comment by LAGGOUNE-Walid** [comment]
It works , thank you .
