### ISSUE TITLE
Missed PHP_FPM_PROCESS_CONTROL_TIMEOUT variable

### ISSUE THREAD

**Issue by beholdr** [serversideup/docker-php#468]
### Steps To Reproduce

When using `serversideup/php:8.3-fpm` after `v3.4.0` release I've got an error on starting container:

<img width="734" alt="SCR-20241017-oqvd" src="https://github.com/user-attachments/assets/0a8f3116-1554-4269-acd5-0ac472d32bfc">

31 line is

```ini
process_control_timeout = ${PHP_FPM_PROCESS_CONTROL_TIMEOUT}
```

Looks like this variable defined only for `fpm-apache` and `fpm-nginx` variants, but not for vanilla `fpm` (and other images). So it’s better to define default value for all images?

#### What did you expect?

Container started

#### What happened instead?

Container can't start

### Affected Docker Images

serversideup/php:8.3-fpm

**Comment by jaydrogers** [comment]
Whoops! Sorry about that.

I just released v3.4.1 with a fix: https://github.com/serversideup/docker-php/releases/tag/v3.4.1

The fix should be available as soon as this build is done: https://github.com/serversideup/docker-php/actions/runs/11386474257
