### ISSUE TITLE
pgrep not found during health check

### ISSUE THREAD

**Issue by hosmelq** [serversideup/docker-php#476]
### Steps To Reproduce

Running the `queue:work` command using the `serversideup/php:8.3-cli ` image.

#### What did you expect?

Health check pass successfully.

#### What happened instead?

Health check fails. 

### Affected Docker Images

serversideup/php:8.3-cli

**Comment by davisenra** [comment]
Had a massive headache this morning trying to understand what was happening. For now I've "fixed" it with the following changes to my Dockerfile:

```Dockerfile
############################################
# Base Image
############################################
FROM serversideup/php:8.3-fpm-nginx-bookworm AS base

USER root

RUN apt-get update && apt-get install -y procps

# continues with my Dockerfile [...]
```

**Comment by jaydrogers** [comment]
Sorry about this!

I must've only tested this in Alpine on accident. For some reason `pgrep` is available in Alpine by default and not in Debian based images. I fixed this in the commit above.

This fix is available in v3.4.5: https://github.com/serversideup/docker-php/releases/tag/v3.4.5

It will be made available as soon as this build is complete: https://github.com/serversideup/docker-php/actions/runs/11447288737

**Comment by davisenra** [comment]
Thanks a lot, @jaydrogers.

Doing the lord's work!

**Comment by jaydrogers** [comment]
You bet! Thanks for posting a proposed solution!
