### ISSUE TITLE
Get Error 413-request-entity-too-large 

### ISSUE THREAD

**Issue by minkbear** [serversideup/docker-php#485]
### Steps To Reproduce

using php:8.2.21-fpm-nginx-v3.3.0 and post data to my API in JSON format sizing around 2M and the get error "413-request-entity-too-large" with default configuration.

How to solve this? Please help.

#### What did you expect?

Not get error

### Affected Docker Images

php:8.2.21-fpm-nginx-v3.3.0

**Comment by jaydrogers** [comment]
I would love to take a look at this for you, but if you give me clear and easy steps to reproduce it would help me out a lot.

Also, taking those same steps and seeing if it happens in v3.4.x would be helpful too

**Comment by minkbear** [comment]
Try to using v3.4.x then any issue. I will open ticket again.

**Comment by jaydrogers** [comment]
I wonder if this is related?

<img width="876" alt="image" src="https://github.com/user-attachments/assets/f4e48921-525b-4b6c-a6f3-a9931298b8cf">

https://serversideup.net/open-source/docker-php/docs/reference/environment-variable-specification

This is what ClaudeAI had to say when I asked it:

<img width="706" alt="image" src="https://github.com/user-attachments/assets/a228b7d9-c409-420e-a1c4-23eff8e0b406">
