### ISSUE TITLE
Fix docs about docker build context

### ISSUE THREAD

**Issue by shinsenter** [serversideup/docker-php#50]
Docker's build context in this example should be placed in a sub directory, lets say ./.docker/ to reduce context size for building custom images, unless you want to copy all your files in webroot folder to your build context.

Including too many assets in the build context can become a performance drain.

https://github.com/serversideup/docker-php/blob/d76db022c596ddeb1316496909bb0012720ad1ac/README.md?plain=1#L285

**Comment by shinsenter** [comment]
Ref: https://docs.docker.com/engine/reference/commandline/build/

**Comment by jaydrogers** [comment]
Thanks, I will update the docs soon.

**Comment by jaydrogers** [comment]
Closing this issue because it's no longer relevant in the new docs. I appreciate your help on bringing this to our attention though!
