### ISSUE TITLE
Laravel queue not processing when run from webuser

### ISSUE THREAD

**Issue by viiy** [serversideup/docker-php#55]
### Current Behavior

When i start container with command "su - webuser -c \"php artisan queue:work --tries=3\"" its not processing queue from redis with no errors.
Also it not processing when i run this command inside container.
But when i run command from root (without su - webuser -c) all work.

### Expected Behavior

Laravel queue work with webuser

### Steps To Reproduce

bitnami/redis:latest
serversideup/php:8.1-fpm-nginx
Laravel 9.5.1
predis: 1.1.9

### Host Operating System

Ubuntu-20.04-amd64

### Docker Version

```markdown
20.10.7
```

**Comment by jaydrogers** [comment]
Hmm.... 🤔

Can you share more details on your set up or send me a reproducible example?

We've been running numerous queues with this set up without any issues.

**Comment by viiy** [comment]
I found the proplem. 
webuser does not see environment variables when "su - webuser -c ..."
but if remove the dash - from the call — all Ok
`su - webuser -c "php artisan queue:work --tries=3"` — not work
`su webuser -c "php artisan queue:work --tries=3"` — work
