### ISSUE TITLE
Ensure `php-redis` is working with PHP 8.2

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#80]
### Affected Docker Images

- 8.2*

### Current Behavior

`php8.2-redis` had to be removed in order to build the 8.2 images.

#### More detail
https://github.com/serversideup/docker-php/issues/60#issuecomment-1259916253

### Expected Behavior

PHP-Redis should be supported by default in our 8.2 images

### Steps To Reproduce

1. Add `php8.2-redis` to the packages file (https://github.com/serversideup/docker-php/blob/dev/src/cli/php-version-packages/8.2.txt)
2. Attempt to build the image

### Host Operating System

Ubuntu 22.04

### Docker Version

```markdown
N/A
```

**Comment by jaydrogers** [comment]
Hey @zigazajc007, thanks for your reply in Discord. I figured moving this discussion into GitHub would be beneficial to keeping this discussion organized.

You mentioned:
<img width="615" alt="image" src="https://user-images.githubusercontent.com/3174134/206809466-acdb8f16-81fd-4dce-ba31-f50edf79857a.png">

Are you suggesting that I just use `php-redis`, not `php8.2-redis`?

**Comment by zigazajc007** [comment]
I didn't tried it, but it's possible that php-redis contains some sort of script that will detect what PHP version you have currently installed and install itself to the right location.

I can try today if installing php-redis will work on 8.2

**Comment by alexjustesen** [comment]
@jaydrogers laravel/sail merged in `php8.2-redis` this morning. I don't have to time to test a build this morning but looks like the issues might be resolved.

https://github.com/laravel/sail/pull/510/files
