### ISSUE TITLE
FPM-NGINX *sometimes* fails to start in local development

### ISSUE THREAD

**Issue by danpastori** [serversideup/docker-php#81]
### Affected Docker Images

beta-8.1-fpm-nginx

### Current Behavior

When I attempt to bring up my containers, and APP_ENV = production, I receive the following error message:
```
s6-rc: fatal: timed out
s6-svlisten1: fatal: timed out
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
[04-Oct-2022 14:25:03] NOTICE: Terminating ...
[04-Oct-2022 14:25:03] NOTICE: exiting, bye-bye!
```

### Expected Behavior

The containers should spin up without any errors.

### Steps To Reproduce

1. Set APP_ENV=production in a laravel app
2. Bring up containers.

### Host Operating System

Mac OS 11.6.8

### Docker Version

```markdown
Client:
 Cloud integration: v1.0.29
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:04:45 2022
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Desktop 4.12.0 (85629)
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:23 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
```


### Anything else?

This could possibly be related to the Laravel automation script not exiting correctly.

**Comment by danpastori** [comment]
The .env might not be the issue. But it could still be related to the health checks. We may need to adjust the time out for the PHP-FPM healthcheck.

**Comment by jaydrogers** [comment]
This could definitely be related to PHP-FPM + NGINX healthchecks with S6.

My theory is S6-Overlay could be getting impatient with the healthchecks (like PiHole experienced: https://github.com/pi-hole/docker-pi-hole/issues/1186#issuecomment-1230542431)

This specifically is the `S6_CMD_WAIT_FOR_SERVICES_MAXTIME` variable that may need adjustment.

We can get connected on screens and do some tests 👍

**Comment by jaydrogers** [comment]
Just deployed a commit on the `dev` branch. This should be resolved in beta and this issue will automatically close upon merge 🚀
