### ISSUE TITLE
Start building out PHP images

### ISSUE THREAD

**Issue by jaydrogers** [serversideup/docker-php#9]
# Background
* We need to figure out how to organize each PHP image

# Structure
For each PHP version, I am thinking of having 3 versions:
1. **cli** (for quick PHP CLI interactions)
1. **fpm** (for apps that need fpm separate from the web server)
1. **fpm-nginx** (for apps that include NGINX + FPM in all in one container)

Each image will depend on eachother, just like [phpdocker-io](https://github.com/phpdocker-io/base-images/tree/master/php/7.4) (Dependency looks like: CLI < FPM < FPM-NGINX)

# Where this adds some challenges
I'll need to update Github actions to:
1. Pull Ubuntu base image
2. Check caches
3. Build CLI images
4. Push CLI images
5. Build FPM images
6. Push CLI images
7. Build FPM-NGINX images
8. Push FPM-NGINX images
9. Automatically tag the latest PHP version as `latest`

Hopefully I can do this without having a mile long Github actions file 😅

# FPM-NGINX
There will probably be a lot of people who will totally disagree with this methodology, but I really do like having the entire app in one container for exact reference points for the app (see this https://www.reddit.com/r/kubernetes/comments/f68s3z/what_is_the_best_way_to_deploy_laravel_in/fi3lsuq)

This methodology was also used in @fideloper's Shipping Docker course, which I really liked.

Offering the other images in this dependency structure should still give people the option to use what they need.

# Next Steps
I will start organizing this and am open to any other comments/feedback.

**Comment by fideloper** [comment]
![source](https://user-images.githubusercontent.com/467411/110498364-de7ef000-80bc-11eb-9cc4-6184b72cb419.gif)

**Comment by szepeviktor** [comment]
Every solution has its use.

1. Monolith: every software runs on 1 host including 1 filesystem
2. Monolith deployed in 1 container, same as 1. - _the entire app in one container_
3. Separate database: dedicated host providing more resources, easy to connect through TCP - slower than UDS
4. Database cluster: higher availability, much greater performance
5. Separate services: static file serving, running the application, other services like a search service written in another language, e.g. https://github.com/meilisearch - you may have to use a **shared filesystem**
6. Service clusters: services can scale - there must be a load-balancer and a fully automatic deploy mechanism for each service

**Comment by jaydrogers** [comment]
# Update where I am leaving off today
* New structure is in place with the dependencies
* I have the Github actions working nicely with the different versions (https://github.com/serversideup/docker-php/actions/runs/637279973)
* I decided to follow the same structure of PHPDocker.io where everything is placed in its own DockerHub repo: https://hub.docker.com/orgs/serversideup/repositories

# Next Steps
Time to start populating things with PHP 🤠
